// ─────────────────────────────────────────────────────────────────────────────
// Hadith data — comprehensive curated set, bundled for offline use.
// Sources: Sunnah.com, IslamicFinder, authentic printed collections.
// ─────────────────────────────────────────────────────────────────────────────

export interface HadithBook {
  id: string;
  name: string;
  arabicName: string;
  author: string;
  total: number;
  description: string;
  color: string;
}

export const HADITH_BOOKS: HadithBook[] = [
  { id: 'bukhari', name: 'Sahih Al-Bukhari', arabicName: 'صحيح البخاري', author: 'Imam Al-Bukhari', total: 7563, description: 'The most authentic collection of hadith, compiled over 16 years by Imam Muhammad ibn Ismail Al-Bukhari.', color: '#2D9B6B' },
  { id: 'muslim', name: 'Sahih Muslim', arabicName: 'صحيح مسلم', author: 'Imam Muslim', total: 7453, description: 'Second most authentic hadith collection. Imam Muslim spent 15 years compiling this monumental work.', color: '#3A7BD5' },
  { id: 'tirmidhi', name: "Jami' At-Tirmidhi", arabicName: 'جامع الترمذي', author: 'Imam At-Tirmidhi', total: 3956, description: 'Comprehensive collection with detailed grading. A student of Imam Bukhari and Abu Dawud.', color: '#8B5CF6' },
  { id: 'abudawud', name: 'Sunan Abu Dawud', arabicName: 'سنن أبي داود', author: 'Imam Abu Dawud', total: 5274, description: 'Focus on jurisprudential hadiths. Contains 4,800 hadiths selected from 500,000.', color: '#D97706' },
  { id: 'ibnmajah', name: 'Sunan Ibn Majah', arabicName: 'سنن ابن ماجه', author: 'Imam Ibn Majah', total: 4341, description: 'Important collection of prophetic traditions covering all aspects of Islamic law.', color: '#DC2626' },
  { id: 'nasai', name: "Sunan An-Nasa'i", arabicName: 'سنن النسائي', author: "Imam An-Nasa'i", total: 5761, description: "Known for strictness in accepting narrators. Called 'Al-Mujtaba' (the selected).", color: '#0891B2' },
  { id: 'malik', name: 'Muwatta Imam Malik', arabicName: 'موطأ الإمام مالك', author: 'Imam Malik', total: 1594, description: "Earliest compiled hadith collection, 'The Smoothed Path'. Praised by Imam Shafi'i.", color: '#059669' },
  { id: 'ahmad', name: 'Musnad Ahmad', arabicName: 'مسند أحمد', author: 'Imam Ahmad ibn Hanbal', total: 27647, description: "Largest collection of prophetic traditions. Imam Ahmad said: 'I compiled this from 750,000 hadiths.'", color: '#7C3AED' },
  { id: 'qudsi', name: '40 Hadith Qudsi', arabicName: 'الأحاديث القدسية', author: 'Compiled by scholars', total: 40, description: 'Sacred hadiths (Hadith Qudsi) where Allah speaks in first person through the Prophet ﷺ. Divine words beyond the Quran.', color: '#C9A84C' },
];

// ─── Topics ──────────────────────────────────────────────────────────────────

export interface HadithTopic {
  id: string;
  label: string;
  icon: string;
}

export const HADITH_TOPICS: HadithTopic[] = [
  { id: 'faith',     label: 'Faith (Iman)',         icon: '✨' },
  { id: 'prayer',    label: 'Prayer (Salah)',        icon: '🕌' },
  { id: 'fasting',   label: 'Fasting (Sawm)',        icon: '🌙' },
  { id: 'zakat',     label: 'Zakat & Charity',       icon: '💰' },
  { id: 'hajj',      label: 'Hajj & Umrah',          icon: '🕋' },
  { id: 'quran',     label: 'Quran & Knowledge',     icon: '📖' },
  { id: 'character', label: 'Character & Manners',   icon: '🌺' },
  { id: 'family',    label: 'Family & Marriage',     icon: '👨‍👩‍👧' },
  { id: 'business',  label: 'Business & Trade',      icon: '🤝' },
  { id: 'dua',       label: 'Dua & Remembrance',     icon: '🤲' },
  { id: 'death',     label: 'Death & Afterlife',     icon: '⚖️' },
  { id: 'ramadan',   label: 'Ramadan',               icon: '🌙' },
  { id: 'jihad',     label: 'Jihad & Sacrifice',     icon: '⚔️' },
  { id: 'prophets',  label: 'Stories of Prophets',   icon: '📿' },
];

// ─── Hadith Interface ─────────────────────────────────────────────────────────

export interface Hadith {
  id: string;
  bookId: string;
  number: number;
  arabic: string;
  english: string;
  urdu: string;
  grade: 'sahih' | 'hasan' | 'daif' | 'mawdu';
  albanGrade?: string;   // Al-Albani's classification, e.g. 'Sahih', 'Hasan', 'Daif'
  narrator: string;
  chapter?: string;
  topics: string[];
}

// ─────────────────────────────────────────────────────────────────────────────
// LOCAL HADITHS — comprehensive curated set
// ─────────────────────────────────────────────────────────────────────────────

export const LOCAL_HADITHS: Hadith[] = [

  // ═══════════════════════════════════════════════════════════════════════════
  // SAHIH AL-BUKHARI
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'b1', bookId: 'bukhari', number: 1,
    arabic: 'إِنَّمَا الأَعْمَالُ بِالنِّيَّاتِ، وَإِنَّمَا لِكُلِّ امْرِئٍ مَا نَوَى',
    english: 'Actions are judged by intentions, and every person will get what they intended.',
    urdu: 'اعمال کا دارومدار نیتوں پر ہے، اور ہر شخص کو وہی ملے گا جو اس نے نیت کی۔',
    grade: 'sahih', narrator: 'Umar ibn al-Khattab (RA)', chapter: 'Revelation',
    topics: ['faith', 'character'],
  },
  {
    id: 'b2', bookId: 'bukhari', number: 8,
    arabic: 'بُنِيَ الإِسْلاَمُ عَلَى خَمْسٍ: شَهَادَةِ أَنْ لاَ إِلَهَ إِلَّا اللَّهُ وَأَنَّ مُحَمَّدًا رَسُولُ اللَّهِ، وَإِقَامِ الصَّلاَةِ، وَإِيتَاءِ الزَّكَاةِ، وَالْحَجِّ، وَصَوْمِ رَمَضَانَ',
    english: 'Islam is built upon five pillars: testifying that there is no god but Allah and that Muhammad is His messenger, establishing prayer, paying Zakat, performing Hajj, and fasting Ramadan.',
    urdu: 'اسلام پانچ ستونوں پر قائم ہے: اللہ کے سوا کوئی معبود نہیں اور محمد ﷺ اللہ کے رسول ہیں کی گواہی، نماز قائم کرنا، زکوٰۃ دینا، حج کرنا اور رمضان کے روزے رکھنا۔',
    grade: 'sahih', narrator: 'Ibn Umar (RA)', chapter: 'Pillars of Islam',
    topics: ['faith', 'prayer', 'zakat', 'hajj', 'fasting'],
  },
  {
    id: 'b3', bookId: 'bukhari', number: 13,
    arabic: 'لاَ يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ',
    english: 'None of you will have faith until he loves for his brother what he loves for himself.',
    urdu: 'تم میں سے کوئی شخص اس وقت تک مومن نہیں ہو سکتا جب تک اپنے بھائی کے لیے وہی پسند نہ کرے جو اپنے لیے پسند کرتا ہے۔',
    grade: 'sahih', narrator: 'Anas ibn Malik (RA)', chapter: 'Faith',
    topics: ['faith', 'character'],
  },
  {
    id: 'b4', bookId: 'bukhari', number: 59,
    arabic: 'مَنْ كَذَبَ عَلَيَّ مُتَعَمِّدًا فَلْيَتَبَوَّأْ مَقْعَدَهُ مِنَ النَّارِ',
    english: 'Whoever intentionally lies about me, let him take his seat in the Fire.',
    urdu: 'جو شخص جان بوجھ کر مجھ پر جھوٹ باندھے وہ اپنا ٹھکانہ جہنم میں تیار کر لے۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Knowledge',
    topics: ['character', 'quran'],
  },
  {
    id: 'b5', bookId: 'bukhari', number: 5063,
    arabic: 'خَيْرُكُمْ مَنْ تَعَلَّمَ الْقُرْآنَ وَعَلَّمَهُ',
    english: 'The best among you are those who learn the Quran and teach it.',
    urdu: 'تم میں سے بہترین وہ ہے جو قرآن سیکھے اور سکھائے۔',
    grade: 'sahih', narrator: 'Uthman ibn Affan (RA)', chapter: 'Quran',
    topics: ['quran'],
  },
  {
    id: 'b6', bookId: 'bukhari', number: 2442,
    arabic: 'اللَّهُ فِي عَوْنِ الْعَبْدِ مَا كَانَ الْعَبْدُ فِي عَوْنِ أَخِيهِ',
    english: 'Allah helps the servant as long as the servant helps his brother.',
    urdu: 'اللہ اس وقت تک بندے کی مدد کرتا رہتا ہے جب تک بندہ اپنے بھائی کی مدد کرتا رہے۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Brotherhood',
    topics: ['character', 'faith'],
  },
  {
    id: 'b7', bookId: 'bukhari', number: 6018,
    arabic: 'مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ فَلْيَقُلْ خَيْرًا أَوْ لِيَصْمُتْ',
    english: 'Whoever believes in Allah and the Last Day should say something good or remain silent.',
    urdu: 'جو اللہ اور آخرت کے دن پر ایمان رکھتا ہو اسے چاہیے کہ اچھی بات کہے یا خاموش رہے۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Good Character',
    topics: ['faith', 'character'],
  },
  {
    id: 'b8', bookId: 'bukhari', number: 6412,
    arabic: 'كُلُّ ابْنِ آدَمَ خَطَّاءٌ، وَخَيْرُ الْخَطَّائِينَ التَّوَّابُونَ',
    english: 'Every son of Adam makes mistakes, and the best of those who make mistakes are those who repent.',
    urdu: 'ہر انسان خطاکار ہے، اور بہترین خطاکار وہ ہیں جو توبہ کرتے ہیں۔',
    grade: 'hasan', narrator: 'Anas ibn Malik (RA)', chapter: 'Repentance',
    topics: ['faith', 'character', 'dua'],
  },
  {
    id: 'b9', bookId: 'bukhari', number: 2767,
    arabic: 'لاَ يَدْخُلُ الْجَنَّةَ مَنْ لاَ يَأْمَنُ جَارُهُ بَوَائِقَهُ',
    english: 'He will not enter Paradise whose neighbor is not safe from his evil.',
    urdu: 'وہ شخص جنت میں نہیں جائے گا جس کا پڑوسی اس کی تکلیفوں سے محفوظ نہ ہو۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Good Character',
    topics: ['character', 'death'],
  },
  {
    id: 'b10', bookId: 'bukhari', number: 3,
    arabic: 'وَإِذَا جَاءَ رَمَضَانُ، فُتِّحَتْ أَبْوَابُ الْجَنَّةِ، وَغُلِّقَتْ أَبْوَابُ جَهَنَّمَ، وَسُلْسِلَتِ الشَّيَاطِينُ',
    english: 'When Ramadan comes, the gates of Paradise are opened, the gates of Hell are closed, and the devils are chained.',
    urdu: 'جب رمضان آتا ہے تو جنت کے دروازے کھول دیے جاتے ہیں، جہنم کے دروازے بند کر دیے جاتے ہیں اور شیاطین کو زنجیروں میں جکڑ دیا جاتا ہے۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Fasting',
    topics: ['ramadan', 'fasting'],
  },
  {
    id: 'b11', bookId: 'bukhari', number: 6502,
    arabic: 'يَقُولُ اللَّهُ تَعَالَى: أَنَا عِنْدَ ظَنِّ عَبْدِي بِي، وَأَنَا مَعَهُ إِذَا ذَكَرَنِي',
    english: 'Allah says: "I am as My servant expects Me to be, and I am with him when he remembers Me."',
    urdu: 'اللہ تعالیٰ فرماتا ہے: میں اپنے بندے کے گمان کے مطابق ہوں، اور جب وہ مجھے یاد کرتا ہے تو میں اس کے ساتھ ہوتا ہوں۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Remembrance of Allah',
    topics: ['dua', 'faith'],
  },
  {
    id: 'b12', bookId: 'bukhari', number: 1385,
    arabic: 'مَا مِنْ مَوْلُودٍ إِلَّا يُولَدُ عَلَى الْفِطْرَةِ، فَأَبَوَاهُ يُهَوِّدَانِهِ أَوْ يُنَصِّرَانِهِ أَوْ يُمَجِّسَانِهِ',
    english: 'Every child is born upon the natural disposition (fitrah), then his parents make him Jewish, Christian, or Zoroastrian.',
    urdu: 'ہر بچہ فطرت پر پیدا ہوتا ہے، پھر اس کے والدین اسے یہودی، عیسائی یا مجوسی بناتے ہیں۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Funerals',
    topics: ['faith', 'family', 'prophets'],
  },
  {
    id: 'b13', bookId: 'bukhari', number: 6940,
    arabic: 'لَيْسَ الْمُؤْمِنُ بِالطَّعَّانِ وَلاَ اللَّعَّانِ وَلاَ الْفَاحِشِ وَلاَ الْبَذِيءِ',
    english: 'The believer does not taunt others, does not curse them, is not obscene, and is not rude.',
    urdu: 'مومن طعنہ باز نہیں ہوتا، لعنت کرنے والا نہیں ہوتا، فحش گو نہیں ہوتا اور بدزبان نہیں ہوتا۔',
    grade: 'sahih', narrator: 'Abdullah ibn Masood (RA)', chapter: 'Good Character',
    topics: ['character', 'faith'],
  },
  {
    id: 'b14', bookId: 'bukhari', number: 2647,
    arabic: 'الْمُسْلِمُ أَخُو الْمُسْلِمِ، لاَ يَظْلِمُهُ وَلاَ يُسْلِمُهُ',
    english: 'A Muslim is the brother of a Muslim; he does not wrong him nor does he hand him over (to the enemy).',
    urdu: 'مسلمان مسلمان کا بھائی ہے، وہ نہ اس پر ظلم کرتا ہے اور نہ اسے دشمن کے حوالے کرتا ہے۔',
    grade: 'sahih', narrator: 'Abdullah ibn Umar (RA)', chapter: 'Oppression',
    topics: ['character', 'faith'],
  },
  {
    id: 'b15', bookId: 'bukhari', number: 79,
    arabic: 'مَثَلُ مَا بَعَثَنِي اللَّهُ بِهِ مِنَ الْهُدَى وَالْعِلْمِ كَمَثَلِ الْغَيْثِ الْكَثِيرِ',
    english: 'The example of guidance and knowledge with which Allah sent me is like heavy rain falling on the earth — some is fertile soil that absorbs rain and produces vegetation.',
    urdu: 'جو ہدایت اور علم دے کر اللہ نے مجھے مبعوث کیا ہے اس کی مثال اس بارش کی طرح ہے جو زمین پر برسے۔',
    grade: 'sahih', narrator: 'Abu Musa Al-Ashari (RA)', chapter: 'Knowledge',
    topics: ['quran', 'faith'],
  },
  {
    id: 'b16', bookId: 'bukhari', number: 304,
    arabic: 'الصَّلَوَاتُ الْخَمْسُ، وَالْجُمُعَةُ إِلَى الْجُمُعَةِ، كَفَّارَاتٌ لِمَا بَيْنَهُنَّ إِذَا اجْتُنِبَتِ الْكَبَائِرُ',
    english: 'The five prayers, and Friday to Friday, are expiations for whatever sins are committed between them, as long as major sins are avoided.',
    urdu: 'پانچ نمازیں اور جمعہ سے جمعہ تک ان کے درمیان کے گناہوں کا کفارہ ہیں، جب تک کبیرہ گناہوں سے اجتناب کیا جائے۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Prayer',
    topics: ['prayer'],
  },
  {
    id: 'b17', bookId: 'bukhari', number: 1502,
    arabic: 'السَّخِيُّ قَرِيبٌ مِنَ اللَّهِ، قَرِيبٌ مِنَ النَّاسِ، قَرِيبٌ مِنَ الْجَنَّةِ، بَعِيدٌ عَنِ النَّارِ',
    english: 'The generous person is close to Allah, close to people, close to Paradise, and far from the Fire.',
    urdu: 'سخی شخص اللہ کے قریب ہے، لوگوں کے قریب ہے، جنت کے قریب ہے، اور جہنم سے دور ہے۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Generosity',
    topics: ['zakat', 'character', 'death'],
  },
  {
    id: 'b18', bookId: 'bukhari', number: 2644,
    arabic: 'إِنَّ أَحَبَّ الأَعْمَالِ إِلَى اللَّهِ أَدْوَمُهَا وَإِنْ قَلَّ',
    english: 'The most beloved deeds to Allah are the most consistent ones, even if they are few.',
    urdu: 'اللہ کو سب سے پسندیدہ وہ عمل ہے جو ہمیشگی سے کیا جائے، خواہ تھوڑا ہو۔',
    grade: 'sahih', narrator: 'Aisha (RA)', chapter: 'Voluntary Prayer',
    topics: ['prayer', 'faith'],
  },
  {
    id: 'b19', bookId: 'bukhari', number: 5094,
    arabic: 'تَزَوَّجُوا الْوَدُودَ الْوَلُودَ فَإِنِّي مُكَاثِرٌ بِكُمُ الأُمَمَ',
    english: 'Marry those who are loving and fertile, for I will be proud of your great numbers before other nations.',
    urdu: 'ایسی عورتوں سے شادی کرو جو محبت کرنے والی اور بچے پیدا کرنے والی ہوں، کیونکہ میں تمہاری کثرت پر دوسری امتوں کے سامنے فخر کروں گا۔',
    grade: 'sahih', narrator: 'Maqil ibn Yasar (RA)', chapter: 'Marriage',
    topics: ['family'],
  },
  {
    id: 'b20', bookId: 'bukhari', number: 6114,
    arabic: 'مَنْ لاَ يَرْحَمُ لاَ يُرْحَمُ',
    english: 'He who does not show mercy will not be shown mercy.',
    urdu: 'جو رحم نہیں کرتا اس پر رحم نہیں کیا جاتا۔',
    grade: 'sahih', narrator: 'Jarir ibn Abdallah (RA)', chapter: 'Mercy',
    topics: ['character', 'faith'],
  },
  {
    id: 'b21', bookId: 'bukhari', number: 5970,
    arabic: 'رِضَا الرَّبِّ فِي رِضَا الْوَالِدِ، وَسَخَطُ الرَّبِّ فِي سَخَطِ الْوَالِدِ',
    english: 'The pleasure of the Lord is in the pleasure of the parent, and the anger of the Lord is in the anger of the parent.',
    urdu: 'رب کی رضا والد کی رضا میں ہے، اور رب کا غضب والد کے غضب میں ہے۔',
    grade: 'sahih', narrator: 'Abdullah ibn Amr (RA)', chapter: 'Parents',
    topics: ['family', 'faith'],
  },
  {
    id: 'b22', bookId: 'bukhari', number: 2152,
    arabic: 'إِيَّاكُمْ وَالظَّنَّ، فَإِنَّ الظَّنَّ أَكْذَبُ الْحَدِيثِ',
    english: 'Beware of suspicion, for suspicion is the most false of speech.',
    urdu: 'بدگمانی سے بچو کیونکہ بدگمانی سب سے جھوٹی بات ہے۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Good Character',
    topics: ['character', 'business'],
  },
  {
    id: 'b23', bookId: 'bukhari', number: 3209,
    arabic: 'إِنَّ اللَّهَ إِذَا أَحَبَّ عَبْدًا نَادَى جِبْرِيلَ: إِنَّ اللَّهَ يُحِبُّ فُلاَنًا فَأَحِبَّهُ',
    english: 'When Allah loves a servant, He calls Jibreel: "Allah loves so-and-so, so love him." Then Jibreel loves him and calls to the inhabitants of the heavens: "Allah loves so-and-so, so love him." The inhabitants of the heavens love him; then acceptance is placed for him on earth.',
    urdu: 'جب اللہ کسی بندے سے محبت کرتا ہے تو جبریل کو پکارتا ہے: اللہ فلاں شخص سے محبت کرتا ہے پس تم بھی اس سے محبت کرو۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Supplication',
    topics: ['faith', 'dua'],
  },
  {
    id: 'b24', bookId: 'bukhari', number: 2125,
    arabic: 'الْبَيِّعَانِ بِالْخِيَارِ مَا لَمْ يَتَفَرَّقَا، فَإِنْ صَدَقَا وَبَيَّنَا بُورِكَ لَهُمَا فِي بَيْعِهِمَا',
    english: 'The buyer and seller have the option (to cancel) as long as they have not separated. If they are truthful and make everything clear, they will be blessed in their transaction.',
    urdu: 'بیچنے اور خریدنے والے کو جدا ہونے تک اختیار ہے۔ اگر دونوں نے سچ بولا اور سب کچھ واضح کیا تو ان کے سودے میں برکت ہوگی۔',
    grade: 'sahih', narrator: 'Hakim ibn Hizam (RA)', chapter: 'Business',
    topics: ['business'],
  },
  {
    id: 'b25', bookId: 'bukhari', number: 5765,
    arabic: 'لَيْسَ الشَّدِيدُ بِالصُّرَعَةِ، إِنَّمَا الشَّدِيدُ الَّذِي يَمْلِكُ نَفْسَهُ عِنْدَ الْغَضَبِ',
    english: 'The strong man is not the one who can wrestle; the strong man is the one who controls himself when angry.',
    urdu: 'طاقتور وہ نہیں جو کشتی میں جیتے، بلکہ طاقتور وہ ہے جو غصے کے وقت اپنے آپ کو قابو میں رکھے۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Good Character',
    topics: ['character'],
  },
  {
    id: 'b26', bookId: 'bukhari', number: 6307,
    arabic: 'يَنْزِلُ رَبُّنَا تَبَارَكَ وَتَعَالَى كُلَّ لَيْلَةٍ إِلَى السَّمَاءِ الدُّنْيَا حِينَ يَبْقَى ثُلُثُ اللَّيْلِ الآخِرُ',
    english: 'Our Lord descends to the lowest heaven every night in the last third of the night and says: "Who supplicates to Me so I may answer? Who asks Me so I may give? Who seeks My forgiveness so I may forgive?"',
    urdu: 'ہمارا رب ہر رات آخری تہائی حصے میں آسمانِ دنیا پر نازل ہوتا ہے اور کہتا ہے: کون ہے جو مجھ سے دعا مانگے میں اسے دوں؟',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Prayer at Night',
    topics: ['prayer', 'dua', 'faith'],
  },
  {
    id: 'b27', bookId: 'bukhari', number: 1458,
    arabic: 'الصَّدَقَةُ لاَ تَنْقُصُ مِنْ مَالٍ',
    english: 'Charity does not decrease wealth.',
    urdu: 'صدقہ مال میں کمی نہیں کرتا۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Zakat',
    topics: ['zakat', 'faith'],
  },
  {
    id: 'b28', bookId: 'bukhari', number: 1521,
    arabic: 'مَنْ حَجَّ لِلَّهِ فَلَمْ يَرْفُثْ وَلَمْ يَفْسُقْ رَجَعَ كَيَوْمِ وَلَدَتْهُ أُمُّهُ',
    english: 'Whoever performs Hajj for Allah and does not commit obscenity or sin returns like the day his mother gave birth to him.',
    urdu: 'جس نے اللہ کے لیے حج کیا اور اس میں کوئی شہوانی بات نہ کی اور فسق نہ کیا، وہ اس دن کی طرح واپس آئے گا جب اس کی ماں نے اسے جنا تھا۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Hajj',
    topics: ['hajj'],
  },
  {
    id: 'b29', bookId: 'bukhari', number: 6094,
    arabic: 'مَنْ صَامَ رَمَضَانَ إِيمَانًا وَاحْتِسَابًا غُفِرَ لَهُ مَا تَقَدَّمَ مِنْ ذَنْبِهِ',
    english: 'Whoever fasts Ramadan with faith and expectation of reward, his past sins are forgiven.',
    urdu: 'جس نے ایمان اور ثواب کی نیت سے رمضان کے روزے رکھے، اس کے پچھلے گناہ معاف کر دیے جائیں گے۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Fasting',
    topics: ['ramadan', 'fasting', 'faith'],
  },
  {
    id: 'b30', bookId: 'bukhari', number: 7492,
    arabic: 'أَحَبُّ الْبِلاَدِ إِلَى اللَّهِ مَسَاجِدُهَا، وَأَبْغَضُ الْبِلاَدِ إِلَى اللَّهِ أَسْوَاقُهَا',
    english: 'The most beloved places to Allah are the mosques, and the most hated places to Allah are the markets.',
    urdu: 'اللہ کو سب سے پسندیدہ جگہیں مسجدیں ہیں اور سب سے ناپسندیدہ جگہیں بازار ہیں۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Prayer',
    topics: ['prayer', 'business'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // SAHIH MUSLIM
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'm1', bookId: 'muslim', number: 223,
    arabic: 'الطَّهُورُ شَطْرُ الإِيمَانِ',
    english: 'Purity is half of faith.',
    urdu: 'پاکی ایمان کا نصف ہے۔',
    grade: 'sahih', narrator: 'Abu Malik Al-Ashari (RA)', chapter: 'Purification',
    topics: ['faith', 'prayer'],
  },
  {
    id: 'm2', bookId: 'muslim', number: 2553,
    arabic: 'إِنَّ اللَّهَ لاَ يَنْظُرُ إِلَى صُوَرِكُمْ وَأَمْوَالِكُمْ، وَلَكِنْ يَنْظُرُ إِلَى قُلُوبِكُمْ وَأَعْمَالِكُمْ',
    english: 'Allah does not look at your appearance or wealth, but He looks at your hearts and deeds.',
    urdu: 'اللہ تمہاری صورتوں اور مالوں کو نہیں دیکھتا، بلکہ تمہارے دلوں اور اعمال کو دیکھتا ہے۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Virtue',
    topics: ['faith', 'character'],
  },
  {
    id: 'm3', bookId: 'muslim', number: 1006,
    arabic: 'إِذَا مَاتَ الإِنْسَانُ انْقَطَعَ عَنْهُ عَمَلُهُ إِلاَّ مِنْ ثَلاَثَةٍ: إِلاَّ مِنْ صَدَقَةٍ جَارِيَةٍ، أَوْ عِلْمٍ يُنْتَفَعُ بِهِ، أَوْ وَلَدٍ صَالِحٍ يَدْعُو لَهُ',
    english: 'When a person dies, all their deeds end except three: a continuing charity, beneficial knowledge, or a righteous child who prays for them.',
    urdu: 'جب انسان مر جاتا ہے تو اس کے اعمال منقطع ہو جاتے ہیں سوائے تین کے: صدقہ جاریہ، وہ علم جس سے فائدہ اٹھایا جائے، یا نیک اولاد جو اس کے لیے دعا کرے۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Charity',
    topics: ['death', 'zakat', 'quran', 'family'],
  },
  {
    id: 'm4', bookId: 'muslim', number: 55,
    arabic: 'لاَ تَحَاسَدُوا، وَلاَ تَنَاجَشُوا، وَلاَ تَبَاغَضُوا، وَلاَ تَدَابَرُوا، وَكُونُوا عِبَادَ اللَّهِ إِخْوَانًا',
    english: 'Do not envy each other, do not outbid each other, do not hate each other, do not turn away from each other — be servants of Allah as brothers.',
    urdu: 'ایک دوسرے سے حسد نہ کرو، بولی نہ لگاؤ، ایک دوسرے سے بغض نہ رکھو، منہ نہ موڑو، اور اللہ کے بندے بھائی بھائی بن کر رہو۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Brotherhood',
    topics: ['character', 'business'],
  },
  {
    id: 'm5', bookId: 'muslim', number: 2564,
    arabic: 'احْرِصْ عَلَى مَا يَنْفَعُكَ، وَاسْتَعِنْ بِاللَّهِ وَلاَ تَعْجَزْ',
    english: 'Be keen to do what benefits you, seek Allah\'s help, and do not give up.',
    urdu: 'اس چیز پر حریص رہو جو تمہیں فائدہ دے، اللہ سے مدد مانگو اور عاجز نہ ہو۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Destiny',
    topics: ['faith', 'dua'],
  },
  {
    id: 'm6', bookId: 'muslim', number: 2699,
    arabic: 'مَنْ سَلَكَ طَرِيقًا يَلْتَمِسُ فِيهِ عِلْمًا سَهَّلَ اللَّهُ لَهُ طَرِيقًا إِلَى الْجَنَّةِ',
    english: 'Whoever travels a path seeking knowledge, Allah will make easy for him a path to Paradise.',
    urdu: 'جو شخص علم حاصل کرنے کے لیے کوئی راستہ اختیار کرے اللہ اس کے لیے جنت کا راستہ آسان کر دیتا ہے۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Knowledge',
    topics: ['quran', 'death'],
  },
  {
    id: 'm7', bookId: 'muslim', number: 2865,
    arabic: 'الدُّنْيَا سِجْنُ الْمُؤْمِنِ وَجَنَّةُ الْكَافِرِ',
    english: 'The world is a prison for the believer and a paradise for the disbeliever.',
    urdu: 'دنیا مومن کے لیے قید خانہ اور کافر کے لیے جنت ہے۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Renunciation',
    topics: ['faith', 'death'],
  },
  {
    id: 'm8', bookId: 'muslim', number: 577,
    arabic: 'صَلاَةُ الْجَمَاعَةِ تَفْضُلُ صَلاَةَ الْفَذِّ بِسَبْعٍ وَعِشْرِينَ دَرَجَةً',
    english: 'Prayer in congregation is superior to the prayer of a single person by twenty-seven degrees.',
    urdu: 'جماعت کی نماز تنہا نماز سے ستائیس درجے افضل ہے۔',
    grade: 'sahih', narrator: 'Abdullah ibn Umar (RA)', chapter: 'Prayer',
    topics: ['prayer'],
  },
  {
    id: 'm9', bookId: 'muslim', number: 2577,
    arabic: 'يَا عِبَادِي، إِنِّي حَرَّمْتُ الظُّلْمَ عَلَى نَفْسِي وَجَعَلْتُهُ بَيْنَكُمْ مُحَرَّمًا فَلاَ تَظَالَمُوا',
    english: 'O My servants, I have forbidden oppression for Myself and have made it forbidden among you, so do not oppress one another.',
    urdu: 'اے میرے بندو! میں نے ظلم کو اپنے اوپر حرام کیا اور تمہارے درمیان بھی اسے حرام قرار دیا، پس ایک دوسرے پر ظلم نہ کرو۔',
    grade: 'sahih', narrator: 'Abu Dharr Al-Ghifari (RA)', chapter: 'Virtue',
    topics: ['faith', 'character'],
  },
  {
    id: 'm10', bookId: 'muslim', number: 4681,
    arabic: 'إِنَّ الدِّينَ يُسْرٌ، وَلَنْ يُشَادَّ الدِّينَ أَحَدٌ إِلاَّ غَلَبَهُ',
    english: 'Religion is ease; whoever makes religion too difficult will be overcome by it. So be balanced.',
    urdu: 'دین آسان ہے، جو شخص دین میں مشقت ڈالے گا وہ اس پر غالب نہیں آ سکے گا۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Prayer',
    topics: ['faith', 'prayer'],
  },
  {
    id: 'm11', bookId: 'muslim', number: 1055,
    arabic: 'كُلُّ سُلاَمَى مِنَ النَّاسِ عَلَيْهِ صَدَقَةٌ كُلَّ يَوْمٍ تَطْلُعُ فِيهِ الشَّمْسُ',
    english: 'Every joint of a person is a charity upon them for every day the sun rises. Reconciling between two people is charity. Helping a person onto their mount is charity. A good word is charity. Every step taken toward the mosque is charity. Removing something harmful from the road is charity.',
    urdu: 'ہر روز جب سورج طلوع ہو تو ہر جوڑ پر صدقہ ہے۔ دو لوگوں کے درمیان انصاف کرنا صدقہ ہے، کسی کو سواری پر بیٹھنے میں مدد دینا صدقہ ہے۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Charity',
    topics: ['zakat', 'character'],
  },
  {
    id: 'm12', bookId: 'muslim', number: 1631,
    arabic: 'أَفْضَلُ الذِّكْرِ لاَ إِلَهَ إِلاَّ اللَّهُ، وَأَفْضَلُ الدُّعَاءِ الْحَمْدُ لِلَّهِ',
    english: 'The best remembrance is "La ilaha illallah", and the best supplication is "Alhamdulillah".',
    urdu: 'سب سے افضل ذکر لا الہ الا اللہ ہے، اور سب سے افضل دعا الحمد للہ ہے۔',
    grade: 'sahih', narrator: 'Jabir ibn Abdallah (RA)', chapter: 'Remembrance',
    topics: ['dua', 'faith'],
  },
  {
    id: 'm13', bookId: 'muslim', number: 2162,
    arabic: 'حَقُّ الْمُسْلِمِ عَلَى الْمُسْلِمِ سِتٌّ: إِذَا لَقِيتَهُ فَسَلِّمْ عَلَيْهِ، وَإِذَا دَعَاكَ فَأَجِبْهُ، وَإِذَا اسْتَنْصَحَكَ فَانْصَحْهُ',
    english: 'The rights of a Muslim upon a Muslim are six: greet him when you meet him, accept his invitation, give him sincere advice when he asks, say "yarhamukallah" when he sneezes, visit him when he is sick, and follow his funeral.',
    urdu: 'مسلمان پر مسلمان کے چھ حق ہیں: ملنے پر سلام کرو، دعوت قبول کرو، نصیحت مانگنے پر خلوص سے نصیحت کرو۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Greetings',
    topics: ['character', 'faith'],
  },
  {
    id: 'm14', bookId: 'muslim', number: 2984,
    arabic: 'إِنَّ اللَّهَ جَمِيلٌ يُحِبُّ الْجَمَالَ',
    english: 'Verily Allah is beautiful and loves beauty.',
    urdu: 'بے شک اللہ خوبصورت ہے اور خوبصورتی کو پسند کرتا ہے۔',
    grade: 'sahih', narrator: 'Abdullah ibn Masood (RA)', chapter: 'Character',
    topics: ['faith', 'character'],
  },
  {
    id: 'm15', bookId: 'muslim', number: 2671,
    arabic: 'إِنَّ اللَّهَ خَلَقَ آدَمَ وَذُرِّيَّتَهُ، وَكَتَبَ فِي اللَّوْحِ الْمَحْفُوظِ ذَلِكَ قَبْلَ أَنْ يَخْلُقَ السَّمَاوَاتِ وَالأَرْضَ',
    english: 'Allah created Adam and his progeny, and recorded everything in the Preserved Tablet before He created the heavens and earth by fifty thousand years.',
    urdu: 'اللہ نے آسمانوں اور زمین کی تخلیق سے پچاس ہزار سال پہلے آدم اور ان کی اولاد کی تقدیر لوحِ محفوظ میں لکھ دی۔',
    grade: 'sahih', narrator: 'Abdullah ibn Amr (RA)', chapter: 'Divine Decree',
    topics: ['faith', 'prophets'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // JAMI' AT-TIRMIDHI
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 't1', bookId: 'tirmidhi', number: 2516,
    arabic: 'اتَّقِ اللَّهَ حَيْثُمَا كُنْتَ، وَأَتْبِعِ السَّيِّئَةَ الْحَسَنَةَ تَمْحُهَا، وَخَالِقِ النَّاسَ بِخُلُقٍ حَسَنٍ',
    english: 'Fear Allah wherever you are, follow a bad deed with a good one and it will wipe it out, and treat people with good character.',
    urdu: 'جہاں بھی ہو اللہ سے ڈرو، برائی کے بعد نیکی کرو جو اسے مٹا دے گی، اور لوگوں کے ساتھ اچھے اخلاق سے پیش آؤ۔',
    grade: 'hasan', albanGrade: 'Sahih', narrator: 'Muadh ibn Jabal (RA)', chapter: 'Good Character',
    topics: ['character', 'faith'],
  },
  {
    id: 't2', bookId: 'tirmidhi', number: 2407,
    arabic: 'كُنْ فِي الدُّنْيَا كَأَنَّكَ غَرِيبٌ أَوْ عَابِرُ سَبِيلٍ',
    english: 'Be in this world as if you are a stranger or a traveler passing through.',
    urdu: 'دنیا میں اس طرح رہو جیسے کہ تم اجنبی ہو یا راستے سے گزرنے والے مسافر ہو۔',
    grade: 'sahih', albanGrade: 'Sahih', narrator: 'Abdullah ibn Umar (RA)', chapter: 'Renunciation',
    topics: ['faith', 'death'],
  },
  {
    id: 't3', bookId: 'tirmidhi', number: 1924,
    arabic: 'أَكْمَلُ الْمُؤْمِنِينَ إِيمَانًا أَحْسَنُهُمْ خُلُقًا',
    english: 'The most complete of believers in faith are those best in character.',
    urdu: 'مومنوں میں سب سے کامل ایمان والے وہ ہیں جو سب سے بہترین اخلاق کے حامل ہیں۔',
    grade: 'sahih', albanGrade: 'Sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Good Character',
    topics: ['character', 'faith'],
  },
  {
    id: 't4', bookId: 'tirmidhi', number: 2687,
    arabic: 'خِيَارُكُمْ خِيَارُكُمْ لِنِسَائِهِمْ',
    english: 'The best of you are those who are best to their wives.',
    urdu: 'تم میں سے بہترین وہ ہے جو اپنی بیویوں کے ساتھ بہترین ہو۔',
    grade: 'sahih', albanGrade: 'Sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Marriage',
    topics: ['family', 'character'],
  },
  {
    id: 't5', bookId: 'tirmidhi', number: 2346,
    arabic: 'إِنَّ الدُّعَاءَ هُوَ الْعِبَادَةُ',
    english: 'Verily, supplication is worship.',
    urdu: 'بے شک دعا ہی عبادت ہے۔',
    grade: 'sahih', albanGrade: 'Sahih', narrator: 'Numan ibn Basheer (RA)', chapter: 'Supplication',
    topics: ['dua', 'faith'],
  },
  {
    id: 't6', bookId: 'tirmidhi', number: 2633,
    arabic: 'مَنْ لَمْ يَشْكُرِ النَّاسَ لَمْ يَشْكُرِ اللَّهَ',
    english: 'He who does not thank people does not thank Allah.',
    urdu: 'جو لوگوں کا شکر نہیں کرتا وہ اللہ کا بھی شکر نہیں کرتا۔',
    grade: 'sahih', albanGrade: 'Sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Gratitude',
    topics: ['character', 'faith'],
  },
  {
    id: 't7', bookId: 'tirmidhi', number: 2678,
    arabic: 'طَلَبُ الْعِلْمِ فَرِيضَةٌ عَلَى كُلِّ مُسْلِمٍ',
    english: 'Seeking knowledge is an obligation upon every Muslim.',
    urdu: 'علم حاصل کرنا ہر مسلمان پر فرض ہے۔',
    grade: 'sahih', albanGrade: 'Sahih', narrator: 'Anas ibn Malik (RA)', chapter: 'Knowledge',
    topics: ['quran'],
  },
  {
    id: 't8', bookId: 'tirmidhi', number: 1975,
    arabic: 'إِنَّمَا بُعِثْتُ لأُتَمِّمَ صَالِحَ الأَخْلاَقِ',
    english: 'I was sent only to perfect good character.',
    urdu: 'مجھے صرف اچھے اخلاق کی تکمیل کے لیے مبعوث کیا گیا ہے۔',
    grade: 'sahih', albanGrade: 'Sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Good Character',
    topics: ['character'],
  },
  {
    id: 't9', bookId: 'tirmidhi', number: 1924,
    arabic: 'مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ فَلْيُكْرِمْ ضَيْفَهُ',
    english: 'Whoever believes in Allah and the Last Day should honour his guest.',
    urdu: 'جو اللہ اور آخرت کے دن پر ایمان رکھتا ہو اسے اپنے مہمان کی عزت کرنی چاہیے۔',
    grade: 'sahih', albanGrade: 'Sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Hospitality',
    topics: ['faith', 'character'],
  },
  {
    id: 't10', bookId: 'tirmidhi', number: 3598,
    arabic: 'يَا ابْنَ آدَمَ، إِنَّكَ لَوْ أَتَيْتَنِي تَمْشِي أَتَيْتُكَ أَرْكُضُ',
    english: 'O son of Adam, if you come to Me walking, I will come to you running.',
    urdu: 'اے ابنِ آدم، اگر تم میری طرف چل کر آؤ گے تو میں تمہاری طرف دوڑتا ہوا آؤں گا۔',
    grade: 'sahih', albanGrade: 'Sahih', narrator: 'Abu Dharr (RA)', chapter: 'Mercy of Allah',
    topics: ['faith', 'dua'],
  },
  {
    id: 't11', bookId: 'tirmidhi', number: 2516,
    arabic: 'لاَ تَقْطَعُوا الأَرْحَامَ وَلاَ تَقَاطَعُوا',
    english: 'Do not sever family ties, and do not cut off from one another.',
    urdu: 'رشتے نہ توڑو اور ایک دوسرے سے تعلق نہ ختم کرو۔',
    grade: 'sahih', albanGrade: 'Sahih', narrator: 'Abu Bakr (RA)', chapter: 'Family Ties',
    topics: ['family', 'character'],
  },
  {
    id: 't12', bookId: 'tirmidhi', number: 1956,
    arabic: 'الْبَرُّ لاَ يَبْلَى، وَالإِثْمُ لاَ يُنْسَى',
    english: 'Righteousness does not wear out, and sin is not forgotten.',
    urdu: 'نیکی پرانی نہیں ہوتی، اور گناہ بھولا نہیں جاتا۔',
    grade: 'hasan', albanGrade: 'Hasan', narrator: 'Mu\'awiyah (RA)', chapter: 'Good Deeds',
    topics: ['faith', 'death'],
  },
  {
    id: 't13', bookId: 'tirmidhi', number: 2945,
    arabic: 'مَنْ قَرَأَ آيَةَ الْكُرْسِيِّ دُبُرَ كُلِّ صَلاَةٍ مَكْتُوبَةٍ لَمْ يَمْنَعْهُ مِنْ دُخُولِ الْجَنَّةِ إِلاَّ أَنْ يَمُوتَ',
    english: 'Whoever recites Ayat al-Kursi after every obligatory prayer, nothing prevents him from entering Paradise except death.',
    urdu: 'جو شخص ہر فرض نماز کے بعد آیة الکرسی پڑھے، اسے جنت میں داخل ہونے سے صرف موت روک سکتی ہے۔',
    grade: 'sahih', albanGrade: 'Sahih', narrator: 'Abu Umamah (RA)', chapter: 'Quran',
    topics: ['quran', 'prayer', 'dua'],
  },
  {
    id: 't14', bookId: 'tirmidhi', number: 1162,
    arabic: 'لَوْ يَعْلَمُ الرَّجُلُ مَا لَهُ فِي أَنْ يَأْتِيَ أَهْلَهُ لَسَارَعَ',
    english: 'If a man knew the reward he has for fulfilling the needs of his family, he would hasten to do so.',
    urdu: 'اگر آدمی کو معلوم ہوتا کہ اپنے اہل کی ضروریات پوری کرنے میں اسے کتنا اجر ملتا ہے تو وہ جلدی کرتا۔',
    grade: 'hasan', albanGrade: 'Hasan', narrator: 'Abu Hurayrah (RA)', chapter: 'Family',
    topics: ['family'],
  },
  {
    id: 't15', bookId: 'tirmidhi', number: 2369,
    arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ',
    english: 'O Allah, I seek refuge in You from grief and sorrow, from weakness and laziness, from miserliness and cowardice, from the burden of debt and from being overcome by men.',
    urdu: 'اے اللہ! میں تجھ سے غم، حزن، کمزوری، سستی، بخل، بزدلی، قرض کے بوجھ اور لوگوں کے غلبے سے پناہ مانگتا ہوں۔',
    grade: 'sahih', albanGrade: 'Sahih', narrator: 'Anas ibn Malik (RA)', chapter: 'Supplication',
    topics: ['dua'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // SUNAN ABU DAWUD
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'ad1', bookId: 'abudawud', number: 4800,
    arabic: 'عَلَيْكُمْ بِالصِّدْقِ، فَإِنَّ الصِّدْقَ يَهْدِي إِلَى الْبِرِّ، وَإِنَّ الْبِرَّ يَهْدِي إِلَى الْجَنَّةِ',
    english: 'Hold fast to truthfulness, for it leads to righteousness, and righteousness leads to Paradise.',
    urdu: 'سچائی کو لازم پکڑو کیونکہ سچائی نیکی کی طرف لے جاتی ہے اور نیکی جنت کی طرف لے جاتی ہے۔',
    grade: 'sahih', narrator: 'Abdullah ibn Masood (RA)', chapter: 'Good Character',
    topics: ['character', 'faith'],
  },
  {
    id: 'ad2', bookId: 'abudawud', number: 1485,
    arabic: 'الدُّعَاءُ مُخُّ الْعِبَادَةِ',
    english: 'Supplication is the essence of worship.',
    urdu: 'دعا عبادت کا مغز ہے۔',
    grade: 'sahih', narrator: 'Anas ibn Malik (RA)', chapter: 'Supplication',
    topics: ['dua', 'faith'],
  },
  {
    id: 'ad3', bookId: 'abudawud', number: 3462,
    arabic: 'مَنْ أَخَذَ شِبْرًا مِنَ الأَرْضِ ظُلْمًا فَإِنَّهُ يُطَوَّقُهُ مِنْ سَبْعِ أَرَضِينَ يَوْمَ الْقِيَامَةِ',
    english: 'Whoever wrongfully takes a hand span of land will have seven earths put around his neck on the Day of Resurrection.',
    urdu: 'جو شخص ظلم سے ایک بالشت زمین لے، قیامت کے دن ساتوں زمینوں کا طوق اس کے گلے میں ڈالا جائے گا۔',
    grade: 'sahih', narrator: 'Saeed ibn Zayd (RA)', chapter: 'Oppression',
    topics: ['business', 'death', 'character'],
  },
  {
    id: 'ad4', bookId: 'abudawud', number: 4090,
    arabic: 'مَنْ لَبِسَ ثَوْبَ شُهْرَةٍ فِي الدُّنْيَا أَلْبَسَهُ اللَّهُ ثَوْبَ مَذَلَّةٍ يَوْمَ الْقِيَامَةِ',
    english: 'Whoever wears a garment of pride and vanity in this world, Allah will clothe him in a garment of humiliation on the Day of Resurrection.',
    urdu: 'جو دنیا میں شہرت کا لباس پہنے، اللہ اسے قیامت کے دن ذلت کا لباس پہنائے گا۔',
    grade: 'sahih', narrator: 'Ibn Umar (RA)', chapter: 'Clothing',
    topics: ['character', 'death'],
  },
  {
    id: 'ad5', bookId: 'abudawud', number: 2540,
    arabic: 'خَيْرُ الصَّدَقَةِ مَا كَانَ عَنْ ظَهْرِ غِنًى',
    english: 'The best charity is what is given when one has more than enough.',
    urdu: 'سب سے بہترین صدقہ وہ ہے جو فراخ دلی کے ساتھ دیا جائے۔',
    grade: 'sahih', narrator: 'Hakim ibn Hizam (RA)', chapter: 'Charity',
    topics: ['zakat'],
  },
  {
    id: 'ad6', bookId: 'abudawud', number: 4261,
    arabic: 'مَنْ رَأَى مِنْكُمْ مُنْكَرًا فَلْيُغَيِّرْهُ بِيَدِهِ، فَإِنْ لَمْ يَسْتَطِعْ فَبِلِسَانِهِ، فَإِنْ لَمْ يَسْتَطِعْ فَبِقَلْبِهِ وَذَلِكَ أَضْعَفُ الإِيمَانِ',
    english: 'Whoever sees an evil, let him change it with his hand. If unable, then with his tongue. If unable, then with his heart — and that is the weakest of faith.',
    urdu: 'تم میں سے جو کوئی برائی دیکھے وہ اسے اپنے ہاتھ سے بدلے، نہ کر سکے تو زبان سے، نہ کر سکے تو دل سے — اور یہ ایمان کا سب سے کمزور درجہ ہے۔',
    grade: 'sahih', narrator: 'Abu Said Al-Khudri (RA)', chapter: 'Commanding Good',
    topics: ['faith', 'character', 'jihad'],
  },
  {
    id: 'ad7', bookId: 'abudawud', number: 869,
    arabic: 'صَلِّ صَلاَةَ مُوَدِّعٍ',
    english: 'Pray as if it were your farewell prayer.',
    urdu: 'ایسے نماز پڑھو جیسے یہ تمہاری آخری نماز ہو۔',
    grade: 'hasan', narrator: 'Abu Ayyub Al-Ansari (RA)', chapter: 'Prayer',
    topics: ['prayer', 'death'],
  },
  {
    id: 'ad8', bookId: 'abudawud', number: 2535,
    arabic: 'الرَّاحِمُونَ يَرْحَمُهُمُ الرَّحْمَنُ، ارْحَمُوا مَنْ فِي الأَرْضِ يَرْحَمْكُمْ مَنْ فِي السَّمَاءِ',
    english: 'Those who show mercy will be shown mercy by the Most Merciful. Show mercy to those on earth, and the One above the heavens will show mercy to you.',
    urdu: 'رحم کرنے والوں پر رحمٰن رحم کرتا ہے۔ زمین والوں پر رحم کرو، آسمان والا تم پر رحم کرے گا۔',
    grade: 'sahih', narrator: 'Abdullah ibn Amr (RA)', chapter: 'Mercy',
    topics: ['character', 'faith'],
  },
  {
    id: 'ad9', bookId: 'abudawud', number: 3664,
    arabic: 'تَهَادَوْا تَحَابُّوا',
    english: 'Exchange gifts and you will love one another.',
    urdu: 'ایک دوسرے کو تحفے دو، آپس میں محبت پیدا ہوگی۔',
    grade: 'hasan', narrator: 'Abu Hurayrah (RA)', chapter: 'Gifts',
    topics: ['character', 'family'],
  },
  {
    id: 'ad10', bookId: 'abudawud', number: 2875,
    arabic: 'الأَعْمَالُ بِالْخَوَاتِيمِ',
    english: 'Deeds are judged by their endings.',
    urdu: 'اعمال کا اعتبار ان کے انجام پر ہوتا ہے۔',
    grade: 'sahih', narrator: 'Sahl ibn Saad (RA)', chapter: 'Divine Decree',
    topics: ['faith', 'death'],
  },
  {
    id: 'ad11', bookId: 'abudawud', number: 1270,
    arabic: 'إِنَّ لِرَبِّكَ عَلَيْكَ حَقًّا، وَلِنَفْسِكَ عَلَيْكَ حَقًّا، وَلأَهْلِكَ عَلَيْكَ حَقًّا',
    english: 'Indeed your Lord has a right upon you, your body has a right upon you, and your family has a right upon you.',
    urdu: 'تمہارے رب کا تم پر حق ہے، تمہارے جسم کا تم پر حق ہے، اور تمہارے اہل کا تم پر حق ہے۔',
    grade: 'sahih', narrator: 'Salman Al-Farsi (RA)', chapter: 'Balance in Worship',
    topics: ['family', 'prayer', 'faith'],
  },
  {
    id: 'ad12', bookId: 'abudawud', number: 4297,
    arabic: 'مَا نَقَصَ مَالٌ مِنْ صَدَقَةٍ، وَمَا زَادَ اللَّهُ عَبْدًا بِعَفْوٍ إِلاَّ عِزًّا',
    english: 'Wealth is not decreased by charity, and Allah does not increase a servant\'s honour except by forgiving.',
    urdu: 'صدقے سے مال کم نہیں ہوتا، اور معاف کرنے سے اللہ بندے کی عزت ہی بڑھاتا ہے۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Charity',
    topics: ['zakat', 'character'],
  },
  {
    id: 'ad13', bookId: 'abudawud', number: 3990,
    arabic: 'إِنَّ أَوَّلَ مَا يُحَاسَبُ بِهِ الْعَبْدُ يَوْمَ الْقِيَامَةِ مِنْ عَمَلِهِ صَلاَتُهُ',
    english: 'The first thing a servant will be held accountable for on the Day of Resurrection is his prayer.',
    urdu: 'قیامت کے دن بندے سے سب سے پہلے اس کی نماز کا حساب لیا جائے گا۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Prayer',
    topics: ['prayer', 'death'],
  },
  {
    id: 'ad14', bookId: 'abudawud', number: 2120,
    arabic: 'اتَّقُوا الدُّنْيَا، وَاتَّقُوا النِّسَاءَ',
    english: 'Beware of the world and beware of women (its temptations).',
    urdu: 'دنیا سے بچو اور عورتوں (کے فتنوں) سے بچو۔',
    grade: 'sahih', narrator: 'Abu Said Al-Khudri (RA)', chapter: 'Trials',
    topics: ['faith'],
  },
  {
    id: 'ad15', bookId: 'abudawud', number: 3101,
    arabic: 'مَنْ أَرَادَ أَنْ يَسْأَلَ اللَّهَ شَيْئًا، فَلْيَسْأَلْهُ',
    english: 'Whoever wants to ask Allah for something, let him ask Allah.',
    urdu: 'جو اللہ سے کچھ مانگنا چاہے، وہ اللہ سے مانگے۔',
    grade: 'hasan', narrator: 'Anas ibn Malik (RA)', chapter: 'Supplication',
    topics: ['dua', 'faith'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // SUNAN IBN MAJAH
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'im1', bookId: 'ibnmajah', number: 224,
    arabic: 'طَلَبُ الْعِلْمِ فَرِيضَةٌ عَلَى كُلِّ مُسْلِمٍ',
    english: 'Seeking knowledge is an obligation upon every Muslim.',
    urdu: 'علم حاصل کرنا ہر مسلمان پر فرض ہے۔',
    grade: 'sahih', albanGrade: 'Sahih', narrator: 'Anas ibn Malik (RA)', chapter: 'Knowledge',
    topics: ['quran'],
  },
  {
    id: 'im2', bookId: 'ibnmajah', number: 2143,
    arabic: 'لاَ تَبِعْ مَا لَيْسَ عِنْدَكَ',
    english: 'Do not sell what you do not possess.',
    urdu: 'وہ چیز مت بیچو جو تمہارے پاس نہیں ہے۔',
    grade: 'sahih', albanGrade: 'Sahih', narrator: 'Hakim ibn Hizam (RA)', chapter: 'Business',
    topics: ['business'],
  },
  {
    id: 'im3', bookId: 'ibnmajah', number: 4341,
    arabic: 'خُذِ الصِّحَّةَ قَبْلَ السَّقَمِ، وَالْحَيَاةَ قَبْلَ الْمَوْتِ',
    english: 'Take advantage of health before illness, and life before death.',
    urdu: 'صحت کو بیماری سے پہلے اور زندگی کو موت سے پہلے غنیمت سمجھو۔',
    grade: 'sahih', albanGrade: 'Sahih', narrator: 'Ibn Abbas (RA)', chapter: 'Renunciation',
    topics: ['faith', 'death'],
  },
  {
    id: 'im4', bookId: 'ibnmajah', number: 1690,
    arabic: 'إِذَا مَرِضَ الْعَبْدُ، أَوْ سَافَرَ، كُتِبَ لَهُ مِثْلُ مَا كَانَ يَعْمَلُ مُقِيمًا صَحِيحًا',
    english: 'When a servant falls ill or travels, the same deeds he used to do while healthy and at home are recorded for him.',
    urdu: 'جب بندہ بیمار پڑے یا سفر کرے، اس کے لیے وہی اعمال لکھے جاتے ہیں جو وہ صحت اور اقامت کی حالت میں کیا کرتا تھا۔',
    grade: 'sahih', narrator: 'Abu Musa Al-Ashari (RA)', chapter: 'Illness',
    topics: ['faith', 'death'],
  },
  {
    id: 'im5', bookId: 'ibnmajah', number: 3749,
    arabic: 'اللَّهُمَّ اغْفِرْ لِي ذَنْبِي كُلَّهُ، دِقَّهُ وَجِلَّهُ، وَأَوَّلَهُ وَآخِرَهُ',
    english: 'O Allah, forgive me all my sins — small and great, first and last, open and hidden.',
    urdu: 'اے اللہ! میرے سارے گناہ بخش دے — چھوٹے اور بڑے، پہلے اور آخری، کھلے اور چھپے۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Supplication',
    topics: ['dua', 'faith'],
  },
  {
    id: 'im6', bookId: 'ibnmajah', number: 4170,
    arabic: 'مَا أَكَلَ أَحَدٌ طَعَامًا قَطُّ خَيْرًا مِنْ أَنْ يَأْكُلَ مِنْ عَمَلِ يَدِهِ',
    english: 'No one has ever eaten food better than what he ate from the work of his own hands.',
    urdu: 'کسی نے کبھی اپنے ہاتھوں کی کمائی سے بہتر کھانا نہیں کھایا۔',
    grade: 'sahih', narrator: 'Al-Miqdad ibn Madikarib (RA)', chapter: 'Earning',
    topics: ['business', 'character'],
  },
  {
    id: 'im7', bookId: 'ibnmajah', number: 3793,
    arabic: 'يَا ابْنَ آدَمَ، تَفَرَّغْ لِعِبَادَتِي أَمْلَأْ صَدْرَكَ غِنًى وَأَسُدَّ فَقْرَكَ',
    english: 'O son of Adam, free yourself for My worship and I will fill your heart with richness and ward off your poverty.',
    urdu: 'اے ابنِ آدم، میری عبادت کے لیے فارغ ہو جا، میں تیرا سینہ غنا سے بھر دوں گا اور تیری فقر دور کر دوں گا۔',
    grade: 'hasan', albanGrade: 'Hasan', narrator: 'Abu Hurayrah (RA)', chapter: 'Worship',
    topics: ['faith', 'dua'],
  },
  {
    id: 'im8', bookId: 'ibnmajah', number: 1420,
    arabic: 'إِذَا قَامَ أَحَدُكُمْ إِلَى الصَّلاَةِ فَلاَ يَبْصُقْ أَمَامَهُ فَإِنَّمَا يُنَاجِي اللَّهَ',
    english: 'When one of you stands for prayer, do not spit in front of him, for he is conversing with Allah.',
    urdu: 'جب تم میں سے کوئی نماز کھڑا ہو تو اس کے آگے نہ تھوکو کیونکہ وہ اللہ سے سرگوشی کر رہا ہوتا ہے۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Prayer',
    topics: ['prayer'],
  },
  {
    id: 'im9', bookId: 'ibnmajah', number: 1850,
    arabic: 'النِّكَاحُ مِنْ سُنَّتِي، فَمَنْ لَمْ يَعْمَلْ بِسُنَّتِي فَلَيْسَ مِنِّي',
    english: 'Marriage is from my Sunnah. Whoever does not follow my Sunnah has nothing to do with me.',
    urdu: 'نکاح میری سنت ہے۔ جس نے میری سنت پر عمل نہ کیا وہ مجھ سے نہیں۔',
    grade: 'sahih', narrator: 'Anas ibn Malik (RA)', chapter: 'Marriage',
    topics: ['family'],
  },
  {
    id: 'im10', bookId: 'ibnmajah', number: 4019,
    arabic: 'إِذَا أَحَبَّ أَحَدُكُمْ أَخَاهُ فَلْيُعْلِمْهُ',
    english: 'If one of you loves his brother, let him inform him.',
    urdu: 'جب تم میں سے کوئی اپنے بھائی سے محبت کرے تو اسے بتائے۔',
    grade: 'hasan', albanGrade: 'Sahih', narrator: 'Al-Miqdad ibn Madikarib (RA)', chapter: 'Brotherhood',
    topics: ['character', 'family'],
  },
  {
    id: 'im11', bookId: 'ibnmajah', number: 3459,
    arabic: 'مَا مَلَأَ آدَمِيٌّ وِعَاءً شَرًّا مِنْ بَطْنٍ',
    english: 'No man fills a vessel worse than his stomach. Sufficient for a person are a few morsels to keep his back straight.',
    urdu: 'کسی آدمی نے پیٹ سے بُرا کوئی برتن نہیں بھرا۔ آدمی کو اتنا کافی ہے جو اس کی پیٹھ سیدھی رکھ سکے۔',
    grade: 'hasan', narrator: 'Miqdad ibn Madikarib (RA)', chapter: 'Eating',
    topics: ['character', 'faith'],
  },
  {
    id: 'im12', bookId: 'ibnmajah', number: 4244,
    arabic: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ',
    english: 'I seek refuge in the perfect words of Allah from the evil of what He has created.',
    urdu: 'میں اللہ کے کامل کلمات کی پناہ لیتا ہوں اس کی مخلوق کے شر سے۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Supplication',
    topics: ['dua'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // SUNAN AN-NASAI
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'n1', bookId: 'nasai', number: 5695,
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ الْهُدَى وَالتُّقَى وَالْعَفَافَ وَالْغِنَى',
    english: 'O Allah, I ask You for guidance, piety, chastity and contentment.',
    urdu: 'اے اللہ! میں تجھ سے ہدایت، پرہیزگاری، پاکدامنی اور بے نیازی مانگتا ہوں۔',
    grade: 'sahih', narrator: 'Abdullah ibn Masood (RA)', chapter: 'Supplication',
    topics: ['dua', 'faith'],
  },
  {
    id: 'n2', bookId: 'nasai', number: 406,
    arabic: 'إِنَّ لِلصَّلاَةِ أَوَّلًا وَآخِرًا',
    english: 'Prayer has a beginning and an end (time window). Whoever prays the first rak\'ah of Asr before sunset has caught the prayer.',
    urdu: 'نماز کا ایک اول اور آخر ہے۔ جس نے سورج ڈوبنے سے پہلے عصر کی ایک رکعت پڑھ لی، اس نے نماز پا لی۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Prayer Times',
    topics: ['prayer'],
  },
  {
    id: 'n3', bookId: 'nasai', number: 3217,
    arabic: 'أَنَّ رَسُولَ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ كَانَ يَقُولُ فِي دُعَائِهِ: رَبِّ أَعِنِّي وَلاَ تُعِنْ عَلَيَّ',
    english: 'The Prophet ﷺ used to say in his supplication: "O Lord, help me and do not help against me; give victory to me and do not give victory over me."',
    urdu: 'نبی ﷺ اپنی دعا میں کہتے: اے رب! میری مدد کر اور میرے خلاف مدد نہ کر، مجھے فتح دے اور مجھ پر فتح نہ دے۔',
    grade: 'sahih', narrator: 'Ibn Abbas (RA)', chapter: 'Supplication',
    topics: ['dua', 'jihad'],
  },
  {
    id: 'n4', bookId: 'nasai', number: 1302,
    arabic: 'أَوَّلُ مَا يُحَاسَبُ بِهِ الْعَبْدُ الصَّلاَةُ، وَأَوَّلُ مَا يُقْضَى بَيْنَ النَّاسِ الدِّمَاءُ',
    english: 'The first thing a servant will be held accountable for is the prayer, and the first thing to be judged between people will be bloodshed.',
    urdu: 'بندے سے سب سے پہلے نماز کا حساب لیا جائے گا، اور لوگوں کے درمیان سب سے پہلے خون کا فیصلہ ہوگا۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Prayer',
    topics: ['prayer', 'death'],
  },
  {
    id: 'n5', bookId: 'nasai', number: 2215,
    arabic: 'صُومُوا لِرُؤْيَتِهِ وَأَفْطِرُوا لِرُؤْيَتِهِ',
    english: 'Fast when you see the crescent, and break your fast when you see it.',
    urdu: 'چاند دیکھ کر روزہ رکھو اور چاند دیکھ کر روزہ افطار کرو۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Fasting',
    topics: ['fasting', 'ramadan'],
  },
  {
    id: 'n6', bookId: 'nasai', number: 4913,
    arabic: 'أَكْثِرُوا ذِكْرَ هَاذِمِ اللَّذَّاتِ: الْمَوْتِ',
    english: 'Remember frequently the destroyer of pleasures: death.',
    urdu: 'لذتوں کو توڑنے والی چیز — موت — کو کثرت سے یاد کرو۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Death',
    topics: ['death', 'faith'],
  },
  {
    id: 'n7', bookId: 'nasai', number: 5506,
    arabic: 'مَنْ آتَاهُ اللَّهُ مَالاً فَلَمْ يُؤَدِّ زَكَاتَهُ مُثِّلَ لَهُ مَالُهُ يَوْمَ الْقِيَامَةِ شُجَاعًا أَقْرَعَ',
    english: 'Whoever Allah gives wealth to but does not pay its zakat — on the Day of Resurrection his wealth will be made to appear as a baldheaded snake with two black dots above the eyes.',
    urdu: 'جسے اللہ نے مال دیا اور اس نے زکوٰۃ ادا نہ کی، قیامت کے دن اس کا مال گنجے سانپ کی شکل میں ظاہر ہوگا۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Zakat',
    topics: ['zakat', 'death'],
  },
  {
    id: 'n8', bookId: 'nasai', number: 1135,
    arabic: 'جُعِلَتْ قُرَّةُ عَيْنِي فِي الصَّلاَةِ',
    english: 'The coolness of my eyes has been placed in prayer.',
    urdu: 'میری آنکھوں کی ٹھنڈک نماز میں رکھی گئی ہے۔',
    grade: 'sahih', narrator: 'Anas ibn Malik (RA)', chapter: 'Prayer',
    topics: ['prayer'],
  },
  {
    id: 'n9', bookId: 'nasai', number: 3057,
    arabic: 'الشُّهَدَاءُ عَلَى بَارِقِ نَهَرٍ بِبَابِ الْجَنَّةِ، فِي قِبَابٍ خَضْرَاءَ',
    english: 'The martyrs are at a river by the gate of Paradise, in green domes.',
    urdu: 'شہدا جنت کے دروازے کے قریب ایک چمکدار ندی کے کنارے سبز گنبدوں میں ہیں۔',
    grade: 'sahih', narrator: 'Ibn Abbas (RA)', chapter: 'Martyrdom',
    topics: ['jihad', 'death'],
  },
  {
    id: 'n10', bookId: 'nasai', number: 1672,
    arabic: 'أَفْضَلُ الأَعْمَالِ الصَّلاَةُ لِوَقْتِهَا',
    english: 'The best of deeds is the prayer performed at its proper time.',
    urdu: 'سب سے افضل عمل وقت پر نماز ادا کرنا ہے۔',
    grade: 'sahih', narrator: 'Ibn Masood (RA)', chapter: 'Prayer',
    topics: ['prayer'],
  },
  {
    id: 'n11', bookId: 'nasai', number: 2578,
    arabic: 'كُلُّ أَمْرٍ ذِي بَالٍ لاَ يُبْدَأُ فِيهِ بِبِسْمِ اللَّهِ فَهُوَ أَجْذَمُ',
    english: 'Every matter of importance that does not begin with "Bismillah" is deficient.',
    urdu: 'ہر اہم کام جو بسم اللہ سے شروع نہ ہو وہ ناقص ہے۔',
    grade: 'hasan', albanGrade: 'Hasan', narrator: 'Abu Hurayrah (RA)', chapter: 'Remembrance',
    topics: ['dua', 'faith'],
  },
  {
    id: 'n12', bookId: 'nasai', number: 5387,
    arabic: 'إِنَّ مِنْ أَكْبَرِ الْكَبَائِرِ الإِشْرَاكَ بِاللَّهِ',
    english: 'Among the greatest of sins is associating partners with Allah.',
    urdu: 'سب سے بڑے گناہوں میں سے اللہ کے ساتھ شرک کرنا ہے۔',
    grade: 'sahih', narrator: 'Abu Bakra (RA)', chapter: 'Major Sins',
    topics: ['faith'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MUWATTA IMAM MALIK
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'mal1', bookId: 'malik', number: 1594,
    arabic: 'تَرَكْتُ فِيكُمْ أَمْرَيْنِ، لَنْ تَضِلُّوا مَا تَمَسَّكْتُمْ بِهِمَا: كِتَابَ اللَّهِ وَسُنَّةَ نَبِيِّهِ',
    english: 'I have left among you two things; you will never go astray as long as you hold fast to them: the Book of Allah and the Sunnah of His Prophet.',
    urdu: 'میں نے تم میں دو چیزیں چھوڑی ہیں، جب تک انہیں مضبوطی سے تھامے رہو گے گمراہ نہیں ہوگے: اللہ کی کتاب اور اس کے نبی کی سنت۔',
    grade: 'sahih', narrator: 'Malik ibn Anas (RA) — Mursal', chapter: 'General',
    topics: ['faith', 'quran'],
  },
  {
    id: 'mal2', bookId: 'malik', number: 473,
    arabic: 'لاَ ضَرَرَ وَلاَ ضِرَارَ',
    english: 'There should be no harm and no reciprocating of harm.',
    urdu: 'نہ نقصان پہنچانا چاہیے اور نہ نقصان کا بدلہ لینا چاہیے۔',
    grade: 'sahih', narrator: 'Abu Said Al-Khudri (RA)', chapter: 'Judgments',
    topics: ['business', 'character'],
  },
  {
    id: 'mal3', bookId: 'malik', number: 240,
    arabic: 'مَنْ أَحَبَّ أَنْ يُبْسَطَ لَهُ فِي رِزْقِهِ، وَيُنْسَأَ لَهُ فِي أَثَرِهِ فَلْيَصِلْ رَحِمَهُ',
    english: 'Whoever wishes to have his provision expanded and his lifespan extended, let him maintain his family ties.',
    urdu: 'جو چاہے کہ اس کا رزق کشادہ ہو اور عمر لمبی ہو، وہ صلہ رحمی کرے۔',
    grade: 'sahih', narrator: 'Anas ibn Malik (RA)', chapter: 'Family Ties',
    topics: ['family'],
  },
  {
    id: 'mal4', bookId: 'malik', number: 1,
    arabic: 'إِنَّمَا جُعِلَ الإِمَامُ لِيُؤْتَمَّ بِهِ، فَإِذَا كَبَّرَ فَكَبِّرُوا',
    english: 'The imam is appointed to be followed. When he says the takbeer, say the takbeer. When he bows, bow. When he says "Sami\'a Allahu liman hamidah", say "Rabbana lakal hamd".',
    urdu: 'امام اس لیے بنایا گیا ہے کہ اس کی پیروی کی جائے۔ جب وہ تکبیر کہے تو تم تکبیر کہو، جب وہ رکوع کرے تو تم رکوع کرو۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Prayer in Congregation',
    topics: ['prayer'],
  },
  {
    id: 'mal5', bookId: 'malik', number: 592,
    arabic: 'الصَّائِمُ فِي عِبَادَةٍ مَا لَمْ يُفْطِرْ وَإِنْ كَانَ عَلَى فِرَاشِهِ',
    english: 'The fasting person is in worship as long as he has not broken his fast, even if lying in his bed.',
    urdu: 'روزہ دار جب تک افطار نہ کرے عبادت میں ہے، خواہ اپنے بستر پر لیٹا ہو۔',
    grade: 'hasan', narrator: 'Ibn Shihab (RA) — Mursal', chapter: 'Fasting',
    topics: ['fasting', 'ramadan'],
  },
  {
    id: 'mal6', bookId: 'malik', number: 1102,
    arabic: 'الإِسْلاَمُ يَعْلُو وَلاَ يُعْلَى عَلَيْهِ',
    english: 'Islam is supreme and nothing can be placed above it.',
    urdu: 'اسلام بالادست ہے، اس پر کوئی برتری نہیں ہو سکتی۔',
    grade: 'sahih', narrator: 'Aaidh ibn Amr (RA)', chapter: 'General',
    topics: ['faith'],
  },
  {
    id: 'mal7', bookId: 'malik', number: 863,
    arabic: 'اتَّقُوا اللَّهَ وَأَصْلِحُوا ذَاتَ بَيْنِكُمْ',
    english: 'Fear Allah and reconcile your differences.',
    urdu: 'اللہ سے ڈرو اور اپنے درمیان صلح کرو۔',
    grade: 'sahih', narrator: 'Abu Ayyub Al-Ansari (RA)', chapter: 'Reconciliation',
    topics: ['character', 'faith'],
  },
  {
    id: 'mal8', bookId: 'malik', number: 1724,
    arabic: 'كُلُّ مَعْرُوفٍ صَدَقَةٌ',
    english: 'Every act of goodness is charity.',
    urdu: 'ہر نیکی صدقہ ہے۔',
    grade: 'sahih', narrator: 'Jabir ibn Abdallah (RA)', chapter: 'Charity',
    topics: ['zakat', 'character'],
  },
  {
    id: 'mal9', bookId: 'malik', number: 3,
    arabic: 'أُمِرْتُ أَنْ أُقَاتِلَ النَّاسَ حَتَّى يَقُولُوا: لاَ إِلَهَ إِلاَّ اللَّهُ',
    english: 'I was commanded to fight the people until they say "La ilaha illallah". Whoever says it, his life and property are protected from me.',
    urdu: 'مجھے حکم دیا گیا کہ لوگوں سے لڑوں حتی کہ وہ لا الہ الا اللہ کہیں۔ جس نے یہ کہا اس کی جان اور مال مجھ سے محفوظ ہوگا۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Jihad',
    topics: ['jihad', 'faith'],
  },
  {
    id: 'mal10', bookId: 'malik', number: 1394,
    arabic: 'أَفْضَلُ الصِّيَامِ بَعْدَ رَمَضَانَ صِيَامُ شَهْرِ اللَّهِ الْمُحَرَّمِ',
    english: 'The best fasting after Ramadan is fasting the month of Muharram.',
    urdu: 'رمضان کے بعد سب سے افضل روزہ اللہ کے مہینے محرم کے روزے ہیں۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Voluntary Fasting',
    topics: ['fasting'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MUSNAD AHMAD
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'ah1', bookId: 'ahmad', number: 17214,
    arabic: 'اعْبُدِ اللَّهَ كَأَنَّكَ تَرَاهُ، فَإِنْ لَمْ تَكُنْ تَرَاهُ فَإِنَّهُ يَرَاكَ',
    english: 'Worship Allah as though you see Him, and if you do not see Him, know that He sees you.',
    urdu: 'اللہ کی عبادت اس طرح کرو جیسے تم اسے دیکھ رہے ہو۔ اگر تم اسے نہیں دیکھتے تو وہ تمہیں دیکھ رہا ہے۔',
    grade: 'sahih', narrator: 'Umar ibn al-Khattab (RA)', chapter: 'Ihsan',
    topics: ['faith', 'prayer'],
  },
  {
    id: 'ah2', bookId: 'ahmad', number: 12153,
    arabic: 'مَنْ أَصْبَحَ مِنْكُمْ آمِنًا فِي سِرْبِهِ، مُعَافًى فِي جَسَدِهِ، عِنْدَهُ قُوتُ يَوْمِهِ، فَكَأَنَّمَا حِيزَتْ لَهُ الدُّنْيَا',
    english: 'Whoever wakes up safe in his dwelling, healthy in his body, and has food for his day — it is as though he has been given the whole world.',
    urdu: 'جو شخص صبح اس حال میں اٹھے کہ اپنے گھر میں محفوظ ہو، جسمانی طور پر تندرست ہو اور دن کی خوراک موجود ہو — گویا دنیا اس کے لیے سمیٹ دی گئی۔',
    grade: 'hasan', narrator: 'Ubayd Allah ibn Mihsan (RA)', chapter: 'Contentment',
    topics: ['faith'],
  },
  {
    id: 'ah3', bookId: 'ahmad', number: 27291,
    arabic: 'وَاتَّقِ دَعْوَةَ الْمَظْلُومِ، فَإِنَّهُ لَيْسَ بَيْنَهَا وَبَيْنَ اللَّهِ حِجَابٌ',
    english: 'Fear the supplication of the oppressed, for there is no veil between it and Allah.',
    urdu: 'مظلوم کی دعا سے ڈرو، کیونکہ اس کے اور اللہ کے درمیان کوئی پردہ نہیں ہے۔',
    grade: 'sahih', narrator: 'Muadh ibn Jabal (RA)', chapter: 'Supplication',
    topics: ['dua', 'character'],
  },
  {
    id: 'ah4', bookId: 'ahmad', number: 6650,
    arabic: 'إِنَّ اللَّهَ لَيُمْلِي لِلظَّالِمِ حَتَّى إِذَا أَخَذَهُ لَمْ يُفْلِتْهُ',
    english: 'Allah gives the oppressor respite until He seizes him, and then He does not let him escape.',
    urdu: 'اللہ ظالم کو مہلت دیتا ہے، یہاں تک کہ جب پکڑتا ہے تو چھوڑتا نہیں۔',
    grade: 'sahih', narrator: 'Abu Musa Al-Ashari (RA)', chapter: 'Divine Decree',
    topics: ['faith', 'character'],
  },
  {
    id: 'ah5', bookId: 'ahmad', number: 17319,
    arabic: 'الْمُؤْمِنُ الْقَوِيُّ خَيْرٌ وَأَحَبُّ إِلَى اللَّهِ مِنَ الْمُؤْمِنِ الضَّعِيفِ',
    english: 'The strong believer is better and more beloved to Allah than the weak believer.',
    urdu: 'قوی مومن اللہ کو کمزور مومن سے بہتر اور زیادہ پسندیدہ ہے۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Strength',
    topics: ['faith', 'jihad'],
  },
  {
    id: 'ah6', bookId: 'ahmad', number: 22211,
    arabic: 'حُبِّبَ إِلَيَّ مِنَ الدُّنْيَا النِّسَاءُ وَالطِّيبُ، وَجُعِلَتْ قُرَّةُ عَيْنِي فِي الصَّلاَةِ',
    english: 'Of this world, women and perfume were made beloved to me, and the coolness of my eyes was placed in prayer.',
    urdu: 'دنیا میں سے عورتیں اور خوشبو مجھے محبوب بنائی گئی ہیں، اور میری آنکھوں کی ٹھنڈک نماز میں رکھی گئی ہے۔',
    grade: 'sahih', narrator: 'Anas ibn Malik (RA)', chapter: 'Prayer',
    topics: ['prayer', 'family'],
  },
  {
    id: 'ah7', bookId: 'ahmad', number: 21251,
    arabic: 'مَا مِنْ شَيْءٍ أَثْقَلُ فِي مِيزَانِ الْمُؤْمِنِ يَوْمَ الْقِيَامَةِ مِنْ حُسْنِ الْخُلُقِ',
    english: 'There is nothing heavier on the scale of the believer on the Day of Resurrection than good character.',
    urdu: 'قیامت کے دن مومن کے میزان میں اچھے اخلاق سے بھاری کوئی چیز نہیں ہوگی۔',
    grade: 'sahih', narrator: 'Abu Darda (RA)', chapter: 'Good Character',
    topics: ['character', 'death'],
  },
  {
    id: 'ah8', bookId: 'ahmad', number: 15517,
    arabic: 'إِيَّاكَ وَالْكَذِبَ، فَإِنَّ الْكَذِبَ يَهْدِي إِلَى الْفُجُورِ، وَالْفُجُورُ يَهْدِي إِلَى النَّارِ',
    english: 'Beware of lying, for it leads to wickedness, and wickedness leads to the Fire.',
    urdu: 'جھوٹ سے بچو، کیونکہ جھوٹ بدکاری کی طرف لے جاتا ہے اور بدکاری جہنم کی طرف۔',
    grade: 'sahih', narrator: 'Abdullah ibn Masood (RA)', chapter: 'Truthfulness',
    topics: ['character', 'death'],
  },
  {
    id: 'ah9', bookId: 'ahmad', number: 3508,
    arabic: 'الْمُؤْمِنُ لِلْمُؤْمِنِ كَالْبُنْيَانِ يَشُدُّ بَعْضُهُ بَعْضًا',
    english: 'The believer to the believer is like a building, each part strengthening the other.',
    urdu: 'مومن مومن کے لیے عمارت کی طرح ہے جس کے مختلف حصے ایک دوسرے کو مضبوط کرتے ہیں۔',
    grade: 'sahih', narrator: 'Abu Musa Al-Ashari (RA)', chapter: 'Brotherhood',
    topics: ['faith', 'character'],
  },
  {
    id: 'ah10', bookId: 'ahmad', number: 12680,
    arabic: 'أَلاَ أُخْبِرُكَ بِخَيْرِ مَا يَكْنِزُهُ الْمَرْءُ؟ الْمَرْأَةُ الصَّالِحَةُ، إِذَا نَظَرَ إِلَيْهَا سَرَّتْهُ',
    english: 'Shall I not tell you about the best treasure a person can have? A righteous wife — when he looks at her she pleases him, when he commands her she obeys, and when he is away she protects herself and his property.',
    urdu: 'کیا میں تمہیں وہ بہترین خزانہ نہ بتاؤں جو انسان جمع کر سکتا ہے؟ نیک عورت — جب وہ اسے دیکھے تو وہ خوش ہو، جب حکم دے تو مانے، اور غیر حاضری میں اپنی حفاظت کرے۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Marriage',
    topics: ['family'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 40 HADITH QUDSI — Divine words of Allah narrated by the Prophet ﷺ
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'q1', bookId: 'qudsi', number: 1,
    arabic: 'أَنَا عِنْدَ ظَنِّ عَبْدِي بِي، فَإِنْ ظَنَّ بِي خَيْرًا فَلَهُ، وَإِنْ ظَنَّ بِي شَرًّا فَلَهُ',
    english: 'I am as My servant thinks of Me. If he thinks good of Me, then good; if he thinks evil of Me, then evil.',
    urdu: 'میں اپنے بندے کے گمان کے مطابق ہوں۔ اگر وہ مجھ سے اچھا گمان رکھے تو اسے اچھا ملے گا، اور اگر بُرا گمان رکھے تو بُرا۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA) — Bukhari & Muslim', chapter: 'Mercy of Allah',
    topics: ['faith', 'dua'],
  },
  {
    id: 'q2', bookId: 'qudsi', number: 2,
    arabic: 'يَا عِبَادِي، إِنِّي حَرَّمْتُ الظُّلْمَ عَلَى نَفْسِي وَجَعَلْتُهُ بَيْنَكُمْ مُحَرَّمًا فَلاَ تَظَالَمُوا. يَا عِبَادِي، كُلُّكُمْ ضَالٌّ إِلاَّ مَنْ هَدَيْتُهُ فَاسْتَهْدُونِي أَهْدِكُمْ',
    english: 'O My servants, I have forbidden oppression for Myself and made it forbidden among you, so do not oppress one another. O My servants, you are all astray except those whom I have guided, so seek guidance from Me and I will guide you.',
    urdu: 'اے میرے بندو! میں نے ظلم کو اپنے اوپر حرام کیا اور تمہارے درمیان بھی حرام قرار دیا۔ اے میرے بندو! تم سب گمراہ ہو سوائے اس کے جسے میں نے ہدایت دی، پس مجھ سے ہدایت مانگو میں تمہیں ہدایت دوں گا۔',
    grade: 'sahih', narrator: 'Abu Dharr Al-Ghifari (RA) — Muslim', chapter: 'Servants of Allah',
    topics: ['faith', 'character', 'dua'],
  },
  {
    id: 'q3', bookId: 'qudsi', number: 3,
    arabic: 'الصِّيَامُ لِي وَأَنَا أَجْزِي بِهِ، يَدَعُ شَهْوَتَهُ وَطَعَامَهُ مِنْ أَجْلِي',
    english: 'Fasting is for Me and I reward for it. He leaves his desires and his food for My sake.',
    urdu: 'روزہ میرے لیے ہے اور میں اس کا بدلہ دوں گا۔ وہ اپنی خواہش اور کھانا میری خاطر چھوڑتا ہے۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA) — Bukhari & Muslim', chapter: 'Fasting',
    topics: ['fasting', 'ramadan', 'faith'],
  },
  {
    id: 'q4', bookId: 'qudsi', number: 4,
    arabic: 'يَا ابْنَ آدَمَ، مَرِضْتُ فَلَمْ تَعُدْنِي، قَالَ: يَا رَبِّ كَيْفَ أَعُودُكَ وَأَنْتَ رَبُّ الْعَالَمِينَ؟ قَالَ: أَمَا عَلِمْتَ أَنَّ عَبْدِي فُلاَنًا مَرِضَ فَلَمْ تَعُدْهُ؟',
    english: 'O son of Adam, I was sick and you did not visit Me. He said: O Lord, how could I visit You when You are the Lord of the worlds? He said: Did you not know that My servant so-and-so was sick and you did not visit him?',
    urdu: 'اے ابنِ آدم! میں بیمار تھا لیکن تم نے میری عیادت نہ کی۔ اس نے کہا: اے رب! میں آپ کی عیادت کیسے کرتا جبکہ آپ ربّ العالمین ہیں؟ فرمایا: کیا تجھے معلوم نہ تھا کہ میرا فلاں بندہ بیمار تھا؟',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA) — Muslim', chapter: 'Rights of Fellow Muslims',
    topics: ['character', 'faith'],
  },
  {
    id: 'q5', bookId: 'qudsi', number: 5,
    arabic: 'رَحْمَتِي غَلَبَتْ غَضَبِي',
    english: 'My Mercy has preceded My Wrath.',
    urdu: 'میری رحمت میرے غضب پر غالب ہے۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA) — Bukhari & Muslim', chapter: 'Mercy of Allah',
    topics: ['faith', 'dua'],
  },
  {
    id: 'q6', bookId: 'qudsi', number: 6,
    arabic: 'أَعْدَدْتُ لِعِبَادِي الصَّالِحِينَ مَا لاَ عَيْنٌ رَأَتْ، وَلاَ أُذُنٌ سَمِعَتْ، وَلاَ خَطَرَ عَلَى قَلْبِ بَشَرٍ',
    english: 'I have prepared for My righteous servants what no eye has seen, no ear has heard, and what has never crossed the mind of any human.',
    urdu: 'میں نے اپنے نیک بندوں کے لیے وہ تیار کیا ہے جو نہ کسی آنکھ نے دیکھا، نہ کسی کان نے سنا، اور نہ کسی انسان کے دل میں خطرہ گزرا۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA) — Bukhari & Muslim', chapter: 'Paradise',
    topics: ['death', 'faith'],
  },
  {
    id: 'q7', bookId: 'qudsi', number: 7,
    arabic: 'مَنْ جَاءَ بِالْحَسَنَةِ فَلَهُ عَشْرُ أَمْثَالِهَا أَوْ أَزِيدُ، وَمَنْ جَاءَ بِالسَّيِّئَةِ فَجَزَاءُ سَيِّئَةٍ مِثْلُهَا أَوْ أَغْفِرُ',
    english: 'Whoever comes with a good deed gets ten times its reward or more. Whoever comes with an evil deed is repaid its like or I forgive.',
    urdu: 'جو نیکی لے کر آئے اسے دس گنا یا اس سے بھی زیادہ ملے گا۔ جو برائی لے کر آئے اسے اتنا ہی ملے گا یا میں معاف کر دوں۔',
    grade: 'sahih', narrator: 'Abu Dharr (RA) — Muslim', chapter: 'Deeds and Rewards',
    topics: ['faith', 'death'],
  },
  {
    id: 'q8', bookId: 'qudsi', number: 8,
    arabic: 'يَا ابْنَ آدَمَ، إِنَّكَ لَوْ أَتَيْتَنِي بِقُرَابِ الأَرْضِ خَطَايَا ثُمَّ لَقِيتَنِي لاَ تُشْرِكُ بِي شَيْئًا لأَتَيْتُكَ بِقُرَابِهَا مَغْفِرَةً',
    english: 'O son of Adam, if you were to come to Me with sins nearly filling the earth, then met Me without associating anything with Me, I would come to you with nearly earth\'s fill of forgiveness.',
    urdu: 'اے ابنِ آدم! اگر تم زمین بھر گناہ لے کر آؤ، پھر مجھ سے اس حال میں ملو کہ میرے ساتھ کچھ شریک نہ کیا ہو، تو میں تمہارے پاس زمین بھر مغفرت لے کر آؤں گا۔',
    grade: 'sahih', narrator: 'Anas ibn Malik (RA) — Tirmidhi', chapter: 'Forgiveness',
    topics: ['faith', 'dua'],
  },
  {
    id: 'q9', bookId: 'qudsi', number: 9,
    arabic: 'مَنْ عَادَى لِي وَلِيًّا فَقَدْ آذَنْتُهُ بِالْحَرْبِ، وَمَا تَقَرَّبَ إِلَيَّ عَبْدِي بِشَيْءٍ أَحَبَّ إِلَيَّ مِمَّا افْتَرَضْتُهُ عَلَيْهِ',
    english: 'Whoever shows hostility to a friend of Mine, I declare war upon him. My servant does not draw near to Me with anything more beloved to Me than what I have obligated upon him.',
    urdu: 'جو میرے کسی ولی سے دشمنی کرے، میں اس سے اعلانِ جنگ کرتا ہوں۔ میرا بندہ کسی ایسی چیز سے میرا قرب نہیں پاتا جو مجھے اس سے زیادہ پسند ہو جو میں نے اس پر فرض کی ہے۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA) — Bukhari', chapter: 'Allah\'s Friends',
    topics: ['faith', 'prayer'],
  },
  {
    id: 'q10', bookId: 'qudsi', number: 10,
    arabic: 'أَنَا مَعَ عَبْدِي إِذَا هُوَ ذَكَرَنِي وَتَحَرَّكَتْ بِي شَفَتَاهُ',
    english: 'I am with My servant when he remembers Me and his lips move with My mention.',
    urdu: 'میں اپنے بندے کے ساتھ ہوتا ہوں جب وہ مجھے یاد کرے اور اس کے ہونٹ میرے ذکر سے ہلیں۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA) — Bukhari', chapter: 'Remembrance',
    topics: ['dua', 'faith'],
  },
  {
    id: 'q11', bookId: 'qudsi', number: 11,
    arabic: 'يَقُولُ اللَّهُ عَزَّ وَجَلَّ: الْكِبْرِيَاءُ رِدَائِي، وَالْعَظَمَةُ إِزَارِي، فَمَنْ نَازَعَنِي وَاحِدًا مِنْهُمَا أَلْقَيْتُهُ فِي النَّارِ',
    english: 'Allah Almighty says: Pride is My cloak and Greatness is My garment. Whoever disputes with Me over either of them, I shall cast him into the Fire.',
    urdu: 'اللہ عزوجل فرماتا ہے: تکبر میری چادر ہے اور عظمت میرا تہبند ہے۔ جو ان میں سے کسی ایک میں مجھ سے جھگڑے، میں اسے آگ میں ڈال دوں گا۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA) — Abu Dawud, Ibn Majah', chapter: 'Arrogance',
    topics: ['faith', 'character'],
  },
  {
    id: 'q12', bookId: 'qudsi', number: 12,
    arabic: 'قَسَمْتُ الصَّلاَةَ بَيْنِي وَبَيْنَ عَبْدِي نِصْفَيْنِ، وَلِعَبْدِي مَا سَأَلَ',
    english: 'I have divided prayer between Myself and My servant into two halves, and My servant shall have what he asks. When the servant says "Al-Hamdulillahi Rabbil-Alamin," Allah says: "My servant has praised Me."',
    urdu: 'میں نے نماز (الفاتحہ) کو اپنے اور اپنے بندے کے درمیان دو حصوں میں تقسیم کیا ہے، اور میرے بندے کے لیے وہی ہے جو اس نے مانگا۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA) — Muslim', chapter: 'Prayer and Al-Fatiha',
    topics: ['prayer', 'faith'],
  },
  {
    id: 'q13', bookId: 'qudsi', number: 13,
    arabic: 'إِذَا أَرَادَ اللَّهُ بِعَبْدِهِ الْخَيْرَ عَجَّلَ لَهُ الْعُقُوبَةَ فِي الدُّنْيَا، وَإِذَا أَرَادَ اللَّهُ بِعَبْدِهِ الشَّرَّ أَمْسَكَ عَنْهُ بِذَنْبِهِ حَتَّى يُوَافِيَ بِهِ يَوْمَ الْقِيَامَةِ',
    english: 'When Allah intends good for His servant, He hastens his punishment in this world. When He intends evil for His servant, He withholds the punishment for his sin until he brings it on the Day of Resurrection.',
    urdu: 'جب اللہ اپنے بندے کے ساتھ بھلائی کا ارادہ کرے تو اسے دنیا میں ہی جلد سزا دے دیتا ہے، اور جب برائی کا ارادہ کرے تو گناہ کی سزا روکے رکھتا ہے یہاں تک کہ قیامت کے دن پوری ملے۔',
    grade: 'sahih', narrator: 'Anas ibn Malik (RA) — Tirmidhi', chapter: 'Trials',
    topics: ['faith', 'death'],
  },
  {
    id: 'q14', bookId: 'qudsi', number: 14,
    arabic: 'إِنَّ اللَّهَ كَتَبَ الْحَسَنَاتِ وَالسَّيِّئَاتِ، ثُمَّ بَيَّنَ ذَلِكَ، فَمَنْ هَمَّ بِحَسَنَةٍ فَلَمْ يَعْمَلْهَا كَتَبَهَا اللَّهُ عِنْدَهُ حَسَنَةً كَامِلَةً',
    english: 'Allah has recorded good deeds and evil deeds. Whoever intends a good deed but does not do it, Allah records it as one full good deed. Whoever intends a good deed and does it, Allah records it as ten to seven hundred times its like.',
    urdu: 'اللہ نے نیکیاں اور گناہ لکھ رکھے ہیں۔ جس نے نیکی کا ارادہ کیا مگر نہ کر سکا، اللہ اسے اپنے پاس پوری نیکی لکھتا ہے۔ اور جس نے ارادہ کیا اور کر دکھایا تو اللہ اسے دس سے سات سو گنا تک لکھتا ہے۔',
    grade: 'sahih', narrator: 'Ibn Abbas (RA) — Bukhari & Muslim', chapter: 'Recording Deeds',
    topics: ['faith', 'death'],
  },
  {
    id: 'q15', bookId: 'qudsi', number: 15,
    arabic: 'يَا ابْنَ آدَمَ، إِنَّكَ مَا دَعَوْتَنِي وَرَجَوْتَنِي غَفَرْتُ لَكَ عَلَى مَا كَانَ فِيكَ وَلاَ أُبَالِي',
    english: 'O son of Adam, as long as you call upon Me and put your hope in Me, I will forgive you for whatever you have done, and I do not mind.',
    urdu: 'اے ابنِ آدم! جب تک تو مجھے پکارتا رہے اور مجھ سے امید رکھے، تیرے جتنے بھی گناہ ہوں میں تجھے معاف کرتا رہوں گا اور مجھے کوئی پروا نہیں۔',
    grade: 'sahih', narrator: 'Anas ibn Malik (RA) — Tirmidhi', chapter: 'Forgiveness',
    topics: ['dua', 'faith'],
  },
  {
    id: 'q16', bookId: 'qudsi', number: 16,
    arabic: 'يَا ابْنَ آدَمَ، لَوْ بَلَغَتْ ذُنُوبُكَ عَنَانَ السَّمَاءِ ثُمَّ اسْتَغْفَرْتَنِي غَفَرْتُ لَكَ',
    english: 'O son of Adam, even if your sins were to reach the clouds of the sky, then you sought My forgiveness, I would forgive you.',
    urdu: 'اے ابنِ آدم! اگر تیرے گناہ آسمان تک پہنچ جائیں، پھر تو مجھ سے مغفرت مانگے، تو میں تجھے معاف کر دوں گا۔',
    grade: 'sahih', narrator: 'Anas ibn Malik (RA) — Tirmidhi', chapter: 'Forgiveness',
    topics: ['dua', 'faith'],
  },
  {
    id: 'q17', bookId: 'qudsi', number: 17,
    arabic: 'يَا عِبَادِي، كُلُّكُمْ جَائِعٌ إِلاَّ مَنْ أَطْعَمْتُهُ، فَاسْتَطْعِمُونِي أُطْعِمْكُمْ',
    english: 'O My servants, all of you are hungry except those I have fed, so ask Me for food and I will feed you.',
    urdu: 'اے میرے بندو! تم سب بھوکے ہو سوائے اس کے جسے میں نے کھلایا۔ پس مجھ سے کھانا مانگو میں تمہیں کھلاؤں گا۔',
    grade: 'sahih', narrator: 'Abu Dharr (RA) — Muslim', chapter: 'Servants of Allah',
    topics: ['faith', 'dua'],
  },
  {
    id: 'q18', bookId: 'qudsi', number: 18,
    arabic: 'يَا عِبَادِي، كُلُّكُمْ عَارٍ إِلاَّ مَنْ كَسَوْتُهُ، فَاسْتَكْسُونِي أَكْسُكُمْ',
    english: 'O My servants, all of you are naked except those I have clothed, so ask Me for clothing and I will clothe you.',
    urdu: 'اے میرے بندو! تم سب ننگے ہو سوائے اس کے جسے میں نے لباس دیا۔ پس مجھ سے لباس مانگو میں تمہیں لباس دوں گا۔',
    grade: 'sahih', narrator: 'Abu Dharr (RA) — Muslim', chapter: 'Servants of Allah',
    topics: ['faith', 'dua'],
  },
  {
    id: 'q19', bookId: 'qudsi', number: 19,
    arabic: 'يَا عِبَادِي، إِنَّكُمْ تُخْطِئُونَ بِاللَّيْلِ وَالنَّهَارِ، وَأَنَا أَغْفِرُ الذُّنُوبَ جَمِيعًا، فَاسْتَغْفِرُونِي أَغْفِرْ لَكُمْ',
    english: 'O My servants, you commit sins by night and by day, and I forgive all sins, so seek My forgiveness and I shall forgive you.',
    urdu: 'اے میرے بندو! تم رات اور دن گناہ کرتے ہو، اور میں سب گناہ معاف کر دیتا ہوں، پس مجھ سے مغفرت مانگو میں تمہیں معاف کروں گا۔',
    grade: 'sahih', narrator: 'Abu Dharr (RA) — Muslim', chapter: 'Servants of Allah',
    topics: ['faith', 'dua'],
  },
  {
    id: 'q20', bookId: 'qudsi', number: 20,
    arabic: 'يَا عِبَادِي، لَوْ أَنَّ أَوَّلَكُمْ وَآخِرَكُمْ وَإِنْسَكُمْ وَجِنَّكُمْ كَانُوا عَلَى أَتْقَى قَلْبِ رَجُلٍ وَاحِدٍ مِنْكُمْ مَا زَادَ ذَلِكَ فِي مُلْكِي شَيْئًا',
    english: 'O My servants, if the first of you and the last of you, humans and jinn, were all as righteous as the most righteous heart among you, that would not increase My dominion in the slightest.',
    urdu: 'اے میرے بندو! اگر تم میں سے اول اور آخر، انسان اور جن سب تم میں سب سے پرہیزگار دل والے شخص کی طرح ہو جائیں تو میری سلطنت میں کچھ اضافہ نہ ہو۔',
    grade: 'sahih', narrator: 'Abu Dharr (RA) — Muslim', chapter: 'Servants of Allah',
    topics: ['faith'],
  },
  {
    id: 'q21', bookId: 'qudsi', number: 21,
    arabic: 'يَا عِبَادِي، لَوْ أَنَّ أَوَّلَكُمْ وَآخِرَكُمْ وَإِنْسَكُمْ وَجِنَّكُمْ كَانُوا عَلَى أَفْجَرِ قَلْبِ رَجُلٍ وَاحِدٍ مِنْكُمْ مَا نَقَصَ ذَلِكَ مِنْ مُلْكِي شَيْئًا',
    english: 'O My servants, if the first of you and the last, humans and jinn, were all as wicked as the most wicked heart among you, that would not decrease My dominion in the slightest.',
    urdu: 'اے میرے بندو! اگر تم سب سے بدترین دل والے شخص کی طرح ہو جائیں، تو میری سلطنت میں ذرا بھی کمی نہ آئے گی۔',
    grade: 'sahih', narrator: 'Abu Dharr (RA) — Muslim', chapter: 'Servants of Allah',
    topics: ['faith'],
  },
  {
    id: 'q22', bookId: 'qudsi', number: 22,
    arabic: 'يَا عِبَادِي، لَوْ أَنَّ أَوَّلَكُمْ وَآخِرَكُمْ وَإِنْسَكُمْ وَجِنَّكُمْ قَامُوا فِي صَعِيدٍ وَاحِدٍ فَسَأَلُونِي فَأَعْطَيْتُ كُلَّ إِنْسَانٍ مَسْأَلَتَهُ مَا نَقَصَ ذَلِكَ مِمَّا عِنْدِي',
    english: 'O My servants, if all of you — first and last, humans and jinn — were to stand in one plain and all asked of Me, and I gave each person what he requested, that would not decrease what I have by even as much as a needle decreases the sea.',
    urdu: 'اے میرے بندو! اگر تم سب ایک میدان میں کھڑے ہو کر مجھ سے مانگو اور میں ہر ایک کو اس کی مرضی دے دوں تو میرے پاس جو ہے اس میں سمندر میں سوئی ڈالنے جتنی بھی کمی نہ آئے۔',
    grade: 'sahih', narrator: 'Abu Dharr (RA) — Muslim', chapter: 'Servants of Allah',
    topics: ['faith', 'dua'],
  },
  {
    id: 'q23', bookId: 'qudsi', number: 23,
    arabic: 'يَا عِبَادِي، إِنَّمَا هِيَ أَعْمَالُكُمْ أُحْصِيهَا لَكُمْ، ثُمَّ أُوَفِّيكُمْ إِيَّاهَا، فَمَنْ وَجَدَ خَيْرًا فَلْيَحْمَدِ اللَّهَ',
    english: 'O My servants, these are your deeds that I am counting for you, then I will pay you in full. Whoever finds good, let him praise Allah; and whoever finds otherwise, let him blame no one but himself.',
    urdu: 'اے میرے بندو! یہ تمہارے اعمال ہیں جنہیں میں تمہارے لیے شمار کرتا ہوں، پھر پورا پورا بدلہ دوں گا۔ جو بھلائی پائے وہ اللہ کی تعریف کرے، اور جو اس کے برعکس پائے وہ اپنے سوا کسی کو ملامت نہ کرے۔',
    grade: 'sahih', narrator: 'Abu Dharr (RA) — Muslim', chapter: 'Servants of Allah',
    topics: ['faith', 'death'],
  },
  {
    id: 'q24', bookId: 'qudsi', number: 24,
    arabic: 'إِنَّ اللَّهَ تَعَالَى يَقُولُ يَوْمَ الْقِيَامَةِ: يَا ابْنَ آدَمَ، مَرِضْتُ فَلَمْ تَعُدْنِي... يَا ابْنَ آدَمَ، اسْتَطْعَمْتُكَ فَلَمْ تُطْعِمْنِي',
    english: 'Allah will say on the Day of Resurrection: "O son of Adam, I was hungry and you did not feed Me." The person will say: "O Lord, how could I feed You when You are the Lord of the worlds?" He will say: "Did you not know that My servant so-and-so was hungry and you did not feed him?"',
    urdu: 'اللہ قیامت کے دن فرمائے گا: اے ابنِ آدم! میں بھوکا تھا لیکن تو نے مجھے کھانا نہیں کھلایا۔ وہ کہے گا: اے رب! میں تجھے کیسے کھلاتا جبکہ تو ربّ العالمین ہے؟',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA) — Muslim', chapter: 'Rights of Muslims',
    topics: ['character', 'zakat', 'death'],
  },
  {
    id: 'q25', bookId: 'qudsi', number: 25,
    arabic: 'يَنْزِلُ رَبُّنَا تَبَارَكَ وَتَعَالَى إِلَى السَّمَاءِ الدُّنْيَا كُلَّ لَيْلَةٍ حِينَ يَبْقَى ثُلُثُ اللَّيْلِ الآخِرُ فَيَقُولُ: مَنْ يَدْعُونِي فَأَسْتَجِيبَ لَهُ؟',
    english: 'Our Lord descends to the lowest heaven every night when the last third of the night remains and says: "Who is calling upon Me so that I may answer him? Who is asking of Me so that I may give to him? Who is seeking My forgiveness so that I may forgive him?"',
    urdu: 'ہمارا رب ہر رات آخری تہائی حصے میں آسمانِ دنیا پر نازل ہوتا ہے اور کہتا ہے: کون ہے جو مجھے پکارے کہ میں اسے جواب دوں؟ کون ہے جو مجھ سے مانگے کہ میں اسے دوں؟',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA) — Bukhari & Muslim', chapter: 'Night Prayer',
    topics: ['prayer', 'dua', 'faith'],
  },
  {
    id: 'q26', bookId: 'qudsi', number: 26,
    arabic: 'إِذَا ذَكَرَنِي عَبْدِي فِي نَفْسِهِ ذَكَرْتُهُ فِي نَفْسِي، وَإِذَا ذَكَرَنِي فِي مَلأٍ ذَكَرْتُهُ فِي مَلأٍ خَيْرٍ مِنْهُمْ',
    english: 'When My servant mentions Me to himself, I mention him to Myself. When he mentions Me in an assembly, I mention him in an assembly greater than theirs.',
    urdu: 'جب میرا بندہ مجھے اپنے دل میں یاد کرتا ہے تو میں اسے اپنے دل میں یاد کرتا ہوں۔ جب وہ مجھے کسی مجلس میں یاد کرتا ہے تو میں اسے اس سے بہتر مجلس میں یاد کرتا ہوں۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA) — Bukhari & Muslim', chapter: 'Remembrance',
    topics: ['dua', 'faith'],
  },
  {
    id: 'q27', bookId: 'qudsi', number: 27,
    arabic: 'مَا تَقَرَّبَ إِلَيَّ عَبْدِي بِشَيْءٍ أَحَبَّ إِلَيَّ مِمَّا افْتَرَضْتُهُ عَلَيْهِ، وَمَا يَزَالُ يَتَقَرَّبُ إِلَيَّ بِالنَّوَافِلِ حَتَّى أُحِبَّهُ',
    english: 'My servant does not draw near to Me with anything more beloved to Me than the obligatory duties. He continues to draw near to Me through voluntary acts until I love him.',
    urdu: 'میرا بندہ کسی ایسی چیز سے میرا قرب نہیں پاتا جو مجھے فرائض سے زیادہ پسند ہو، اور وہ نوافل کے ذریعے قرب حاصل کرتا رہتا ہے یہاں تک کہ میں اس سے محبت کرنے لگتا ہوں۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA) — Bukhari', chapter: 'Closeness to Allah',
    topics: ['prayer', 'faith'],
  },
  {
    id: 'q28', bookId: 'qudsi', number: 28,
    arabic: 'إِذَا أَحَبَّ اللَّهُ عَبْدًا نَادَى جِبْرِيلَ: إِنَّ اللَّهَ يُحِبُّ فُلاَنًا فَأَحِبَّهُ، فَيُحِبُّهُ جِبْرِيلُ، ثُمَّ يُنَادِي فِي السَّمَاءِ',
    english: 'When Allah loves a servant, He calls to Jibreel: "Allah loves so-and-so, so love him." Jibreel loves him and calls to the inhabitants of the heavens: "Allah loves so-and-so, so love him." So the inhabitants of the heavens love him, and acceptance is placed for him on earth.',
    urdu: 'جب اللہ کسی بندے سے محبت کرتا ہے تو جبریل کو پکارتا ہے: اللہ فلاں سے محبت کرتا ہے پس تم بھی اس سے محبت کرو۔ جبریل اس سے محبت کرتے ہیں، پھر آسمان والوں میں ندا دیتے ہیں۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA) — Bukhari & Muslim', chapter: 'Love of Allah',
    topics: ['faith'],
  },
  {
    id: 'q29', bookId: 'qudsi', number: 29,
    arabic: 'اشْتَدَّ غَضَبُ اللَّهِ عَلَى قَوْمٍ فَعَلُوا بِنَبِيِّهِ — وَأَشَارَ إِلَى رَبَاعِيَتِهِ — اشْتَدَّ غَضَبُ اللَّهِ عَلَى رَجُلٍ يَقْتُلُهُ رَسُولُ اللَّهِ فِي سَبِيلِ اللَّهِ',
    english: 'Allah\'s anger intensifies against a people who harm His Prophet. Allah\'s anger intensifies against a man killed by the Messenger of Allah in the cause of Allah.',
    urdu: 'اللہ کا غضب اس قوم پر سخت ہوتا ہے جو اس کے نبی کو تکلیف دے۔ اللہ کا غضب اس شخص پر سخت ہوتا ہے جسے رسول اللہ اللہ کی راہ میں قتل کریں۔',
    grade: 'sahih', narrator: 'Anas ibn Malik (RA) — Bukhari & Muslim', chapter: 'Honoring the Prophet',
    topics: ['faith', 'jihad'],
  },
  {
    id: 'q30', bookId: 'qudsi', number: 30,
    arabic: 'أَنَا أَغْنَى الشُّرَكَاءِ عَنِ الشِّرْكِ، مَنْ عَمِلَ عَمَلاً أَشْرَكَ فِيهِ مَعِي غَيْرِي تَرَكْتُهُ وَشِرْكَهُ',
    english: 'I am the most self-sufficient of all partners against partnership. Whoever performs a deed in which he associates anyone with Me, I will leave him and his partner.',
    urdu: 'میں شریک رکھنے سے سب سے زیادہ بے نیاز ہوں۔ جس نے کوئی عمل کیا جس میں میرے ساتھ کوئی دوسرا شریک تھا، میں اسے اور اس کے شرک کو چھوڑ دیتا ہوں۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA) — Muslim', chapter: 'Sincerity',
    topics: ['faith'],
  },
  {
    id: 'q31', bookId: 'qudsi', number: 31,
    arabic: 'إِنِّي وَالْجِنَّ وَالإِنْسَ فِي نَبَإٍ عَظِيمٍ، أَخْلُقُ وَيُعْبَدُ غَيْرِي، أَرْزُقُ وَيُشْكَرُ غَيْرِي',
    english: 'I and jinn and mankind are in a great affair — I create and other than Me is worshipped, I provide sustenance and thanks are given to other than Me.',
    urdu: 'میں اور جن و انسان ایک بڑی خبر میں ہیں — میں پیدا کرتا ہوں اور غیر کی عبادت ہوتی ہے، میں رزق دیتا ہوں اور غیر کا شکر ادا کیا جاتا ہے۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA)', chapter: 'Ingratitude',
    topics: ['faith'],
  },
  {
    id: 'q32', bookId: 'qudsi', number: 32,
    arabic: 'يَقُولُ اللَّهُ تَعَالَى: أَنَا مَعَ عَبْدِي مَا ذَكَرَنِي وَتَحَرَّكَتْ بِي شَفَتَاهُ',
    english: 'Allah says: I am with My servant when he remembers Me and when his lips move in My mention.',
    urdu: 'اللہ تعالیٰ فرماتا ہے: میں اپنے بندے کے ساتھ ہوتا ہوں جب وہ مجھے یاد کرتا ہے اور میرے ذکر میں اس کے ہونٹ ہلتے ہیں۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA) — Ibn Majah', chapter: 'Remembrance',
    topics: ['dua', 'faith'],
  },
  {
    id: 'q33', bookId: 'qudsi', number: 33,
    arabic: 'ابْنَ آدَمَ، أَنْفِقْ أُنْفِقْ عَلَيْكَ',
    english: 'O son of Adam, spend and I will spend on you.',
    urdu: 'اے ابنِ آدم! خرچ کر، میں تجھ پر خرچ کروں گا۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA) — Bukhari & Muslim', chapter: 'Charity',
    topics: ['zakat', 'faith'],
  },
  {
    id: 'q34', bookId: 'qudsi', number: 34,
    arabic: 'يَدُ اللَّهِ مَلأَى لاَ تَغِيضُهَا نَفَقَةٌ، سَحَّاءُ اللَّيْلَ وَالنَّهَارَ',
    english: 'The Hand of Allah is full and is not diminished by spending, overflowing night and day.',
    urdu: 'اللہ کا ہاتھ بھرا ہوا ہے، خرچ کرنے سے کم نہیں ہوتا، وہ رات اور دن بہاتا رہتا ہے۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA) — Bukhari & Muslim', chapter: 'Generosity of Allah',
    topics: ['zakat', 'faith'],
  },
  {
    id: 'q35', bookId: 'qudsi', number: 35,
    arabic: 'إِنَّ اللَّهَ خَلَقَ الرَّحْمَةَ يَوْمَ خَلَقَهَا مِائَةَ رَحْمَةٍ، فَأَمْسَكَ عِنْدَهُ تِسْعًا وَتِسْعِينَ رَحْمَةً',
    english: 'Allah created mercy on the day He created it — one hundred mercies. He kept ninety-nine with Himself and sent down one mercy to the earth. Through that one mercy, creatures show compassion to one another.',
    urdu: 'اللہ نے رحمت پیدا کی — سو رحمتیں۔ ننانوے اپنے پاس رکھیں اور ایک زمین پر اتاری۔ اسی ایک رحمت سے مخلوق ایک دوسرے پر رحم کرتی ہے۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA) — Bukhari', chapter: 'Mercy of Allah',
    topics: ['faith', 'character'],
  },
  {
    id: 'q36', bookId: 'qudsi', number: 36,
    arabic: 'إِنَّ اللَّهَ كَتَبَ عَلَى ابْنِ آدَمَ حَظَّهُ مِنَ الزِّنَا أَدْرَكَ ذَلِكَ لاَ مَحَالَةَ',
    english: 'Allah has written for the son of Adam his share of adultery which he will inevitably commit. The adultery of the eye is the (lustful) look, the adultery of the tongue is the (lustful) speech, and the soul desires and yearns — the private parts then either act upon this or do not.',
    urdu: 'اللہ نے ابنِ آدم کے لیے زنا کا حصہ لکھ دیا جو اسے لازماً ملے گا۔ آنکھوں کا زنا (حرام) نگاہ ہے، زبان کا زنا (حرام) بات ہے، نفس خواہش اور آرزو کرتا ہے — شرمگاہ پھر یا کرتی ہے یا نہیں۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA) — Bukhari & Muslim', chapter: 'Guarding the Limbs',
    topics: ['character', 'faith'],
  },
  {
    id: 'q37', bookId: 'qudsi', number: 37,
    arabic: 'لِكُلِّ عَمَلٍ كَفَّارَةٌ، وَالصَّوْمُ لِي وَأَنَا أَجْزِي بِهِ',
    english: 'For every deed there is an expiation, but fasting is for Me and I reward for it.',
    urdu: 'ہر عمل کا کفارہ ہے، لیکن روزہ میرے لیے ہے اور میں ہی اس کا بدلہ دوں گا۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA) — Bukhari', chapter: 'Fasting',
    topics: ['fasting', 'faith'],
  },
  {
    id: 'q38', bookId: 'qudsi', number: 38,
    arabic: 'قَالَ اللَّهُ تَعَالَى: الْمُتَحَابُّونَ فِي جَلاَلِي لَهُمْ مَنَابِرُ مِنْ نُورٍ يَغْبِطُهُمُ النَّبِيُّونَ وَالشُّهَدَاءُ',
    english: 'Allah says: Those who love one another for My Glory will have pulpits of light, and the prophets and martyrs will envy them.',
    urdu: 'اللہ تعالیٰ فرماتا ہے: میری بزرگی کی خاطر ایک دوسرے سے محبت کرنے والوں کے لیے نور کے منبر ہوں گے جن پر انبیاء اور شہداء بھی رشک کریں گے۔',
    grade: 'sahih', narrator: 'Muadh ibn Jabal (RA) — Tirmidhi', chapter: 'Love for Allah\'s Sake',
    topics: ['faith', 'character', 'death'],
  },
  {
    id: 'q39', bookId: 'qudsi', number: 39,
    arabic: 'قَالَ اللَّهُ: أَيْنَ الْمُتَحَابُّونَ بِجَلاَلِي؟ الْيَوْمَ أُظِلُّهُمْ فِي ظِلِّي يَوْمَ لاَ ظِلَّ إِلاَّ ظِلِّي',
    english: 'Allah will say on the Day of Judgment: "Where are those who loved one another for My Glory? Today I shall shade them under My shade on the day when there is no shade except My shade."',
    urdu: 'اللہ فرمائے گا: کہاں ہیں وہ جو میری بزرگی کی خاطر ایک دوسرے سے محبت کرتے تھے؟ آج میں انہیں اپنے سائے میں رکھوں گا، اس دن جب میرے سائے کے سوا کوئی سایہ نہ ہوگا۔',
    grade: 'sahih', narrator: 'Abu Hurayrah (RA) — Muslim', chapter: 'Day of Judgment',
    topics: ['death', 'faith', 'character'],
  },
  {
    id: 'q40', bookId: 'qudsi', number: 40,
    arabic: 'يَقُولُ اللَّهُ تَعَالَى يَوْمَ الْقِيَامَةِ: يَا آدَمُ، فَيَقُولُ: لَبَّيْكَ رَبَّنَا وَسَعْدَيْكَ، فَيُنَادَى بِصَوْتٍ: إِنَّ اللَّهَ يَأْمُرُكَ أَنْ تُخْرِجَ مِنْ ذُرِّيَّتِكَ بَعْثًا إِلَى النَّارِ',
    english: 'Allah will say on the Day of Resurrection: "O Adam!" Adam will reply: "At Your service, our Lord." A voice will call out: "Allah commands you to bring forth from your progeny a group destined for the Fire."',
    urdu: 'قیامت کے دن اللہ تعالیٰ فرمائے گا: اے آدم! آدم عرض کریں گے: میں حاضر ہوں، اے ہمارے رب! ندا آئے گی: اللہ تمہیں حکم دیتا ہے کہ اپنی اولاد میں سے جہنم کی طرف جانے والوں کو نکالو۔',
    grade: 'sahih', narrator: 'Abu Said Al-Khudri (RA) — Bukhari & Muslim', chapter: 'Day of Judgment',
    topics: ['death', 'faith', 'prophets'],
  },
];
