export interface Name {
  id: number;
  arabic: string;
  transliteration: string;
  meaning: string;
  urduMeaning: string;
  benefit: string;
}

export const NAMES_OF_ALLAH: Name[] = [
  { id: 1, arabic: 'اللَّهُ', transliteration: 'Allah', meaning: 'The Greatest Name', urduMeaning: 'اللہ', benefit: 'The supreme name of God encompassing all attributes.' },
  { id: 2, arabic: 'الرَّحْمَنُ', transliteration: 'Ar-Rahman', meaning: 'The Most Gracious', urduMeaning: 'نہایت مہربان', benefit: 'Recite to gain Allah\'s mercy and compassion.' },
  { id: 3, arabic: 'الرَّحِيمُ', transliteration: 'Ar-Rahim', meaning: 'The Most Merciful', urduMeaning: 'بہت رحم کرنے والا', benefit: 'Recite for Allah\'s continuous mercy.' },
  { id: 4, arabic: 'الْمَلِكُ', transliteration: 'Al-Malik', meaning: 'The Sovereign', urduMeaning: 'بادشاہ', benefit: 'Recite to gain honor and dignity.' },
  { id: 5, arabic: 'الْقُدُّوسُ', transliteration: 'Al-Quddus', meaning: 'The Holy', urduMeaning: 'پاک', benefit: 'Recite to purify the heart.' },
  { id: 6, arabic: 'السَّلاَمُ', transliteration: 'As-Salam', meaning: 'The Source of Peace', urduMeaning: 'سلامتی دینے والا', benefit: 'Recite for peace and safety.' },
  { id: 7, arabic: 'الْمُؤْمِنُ', transliteration: 'Al-Mumin', meaning: 'The Guardian of Faith', urduMeaning: 'امن دینے والا', benefit: 'Recite for protection from fear.' },
  { id: 8, arabic: 'الْمُهَيْمِنُ', transliteration: 'Al-Muhaymin', meaning: 'The Protector', urduMeaning: 'نگہبان', benefit: 'Recite for Allah\'s protection.' },
  { id: 9, arabic: 'الْعَزِيزُ', transliteration: 'Al-Aziz', meaning: 'The Almighty', urduMeaning: 'غالب', benefit: 'Recite to overcome difficulties.' },
  { id: 10, arabic: 'الْجَبَّارُ', transliteration: 'Al-Jabbar', meaning: 'The Compeller', urduMeaning: 'جبار', benefit: 'Recite when you feel broken to be made whole.' },
  { id: 11, arabic: 'الْمُتَكَبِّرُ', transliteration: 'Al-Mutakabbir', meaning: 'The Supreme', urduMeaning: 'بزرگ', benefit: 'Recite to gain true humility.' },
  { id: 12, arabic: 'الْخَالِقُ', transliteration: 'Al-Khaliq', meaning: 'The Creator', urduMeaning: 'خالق', benefit: 'Recite to seek creative solutions.' },
  { id: 13, arabic: 'الْبَارِئُ', transliteration: 'Al-Bari', meaning: 'The Originator', urduMeaning: 'پیدا کرنے والا', benefit: 'Recite for relief from illness.' },
  { id: 14, arabic: 'الْمُصَوِّرُ', transliteration: 'Al-Musawwir', meaning: 'The Fashioner', urduMeaning: 'صورت بنانے والا', benefit: 'Recite for good offspring.' },
  { id: 15, arabic: 'الْغَفَّارُ', transliteration: 'Al-Ghaffar', meaning: 'The Forgiving', urduMeaning: 'بخشنے والا', benefit: 'Recite for forgiveness of sins.' },
  { id: 16, arabic: 'الْقَهَّارُ', transliteration: 'Al-Qahhar', meaning: 'The Subduer', urduMeaning: 'قہار', benefit: 'Recite to overcome enemies.' },
  { id: 17, arabic: 'الْوَهَّابُ', transliteration: 'Al-Wahhab', meaning: 'The Bestower', urduMeaning: 'بہت عطا کرنے والا', benefit: 'Recite to receive abundant blessings.' },
  { id: 18, arabic: 'الرَّزَّاقُ', transliteration: 'Ar-Razzaq', meaning: 'The Provider', urduMeaning: 'رزق دینے والا', benefit: 'Recite for increased provision and rizq.' },
  { id: 19, arabic: 'الْفَتَّاحُ', transliteration: 'Al-Fattah', meaning: 'The Opener', urduMeaning: 'کھولنے والا', benefit: 'Recite to open doors of opportunity.' },
  { id: 20, arabic: 'الْعَلِيمُ', transliteration: 'Al-Alim', meaning: 'The All-Knowing', urduMeaning: 'سب کچھ جاننے والا', benefit: 'Recite to gain knowledge and wisdom.' },
  { id: 21, arabic: 'الْقَابِضُ', transliteration: 'Al-Qabid', meaning: 'The Constrictor', urduMeaning: 'روکنے والا', benefit: 'Recite for contentment.' },
  { id: 22, arabic: 'الْبَاسِطُ', transliteration: 'Al-Basit', meaning: 'The Expander', urduMeaning: 'فراخی دینے والا', benefit: 'Recite for expansion in provision and heart.' },
  { id: 23, arabic: 'الْخَافِضُ', transliteration: 'Al-Khafid', meaning: 'The Abaser', urduMeaning: 'پست کرنے والا', benefit: 'Recite for protection from arrogant enemies.' },
  { id: 24, arabic: 'الرَّافِعُ', transliteration: 'Ar-Rafi', meaning: 'The Exalter', urduMeaning: 'بلند کرنے والا', benefit: 'Recite to raise your status.' },
  { id: 25, arabic: 'الْمُعِزُّ', transliteration: 'Al-Muizz', meaning: 'The Honorer', urduMeaning: 'عزت دینے والا', benefit: 'Recite for honor and dignity.' },
  { id: 26, arabic: 'الْمُذِلُّ', transliteration: 'Al-Mudhill', meaning: 'The Dishonourer', urduMeaning: 'ذلیل کرنے والا', benefit: 'Recite for protection from humiliation.' },
  { id: 27, arabic: 'السَّمِيعُ', transliteration: 'As-Sami', meaning: 'The All-Hearing', urduMeaning: 'سننے والا', benefit: 'Recite when making dua - Allah hears you.' },
  { id: 28, arabic: 'الْبَصِيرُ', transliteration: 'Al-Basir', meaning: 'The All-Seeing', urduMeaning: 'دیکھنے والا', benefit: 'Recite for clear vision and insight.' },
  { id: 29, arabic: 'الْحَكَمُ', transliteration: 'Al-Hakam', meaning: 'The Judge', urduMeaning: 'فیصلہ کرنے والا', benefit: 'Recite for justice in disputes.' },
  { id: 30, arabic: 'الْعَدْلُ', transliteration: 'Al-Adl', meaning: 'The Just', urduMeaning: 'انصاف کرنے والا', benefit: 'Recite for justice and fairness.' },
  { id: 31, arabic: 'اللَّطِيفُ', transliteration: 'Al-Latif', meaning: 'The Subtle One', urduMeaning: 'مہربان', benefit: 'Recite for subtle divine help in difficulties.' },
  { id: 32, arabic: 'الْخَبِيرُ', transliteration: 'Al-Khabir', meaning: 'The All-Aware', urduMeaning: 'خبردار', benefit: 'Recite to be guided away from bad decisions.' },
  { id: 33, arabic: 'الْحَلِيمُ', transliteration: 'Al-Halim', meaning: 'The Forebearing', urduMeaning: 'بردبار', benefit: 'Recite for patience and forbearance.' },
  { id: 34, arabic: 'الْعَظِيمُ', transliteration: 'Al-Azim', meaning: 'The Magnificent', urduMeaning: 'عظیم', benefit: 'Recite to gain awareness of Allah\'s greatness.' },
  { id: 35, arabic: 'الْغَفُورُ', transliteration: 'Al-Ghafur', meaning: 'The Forgiving', urduMeaning: 'معاف کرنے والا', benefit: 'Recite for complete forgiveness.' },
  { id: 36, arabic: 'الشَّكُورُ', transliteration: 'Ash-Shakur', meaning: 'The Grateful', urduMeaning: 'قدر دان', benefit: 'Recite to increase gratitude and blessings.' },
  { id: 37, arabic: 'الْعَلِيُّ', transliteration: 'Al-Ali', meaning: 'The Most High', urduMeaning: 'سب سے بلند', benefit: 'Recite to be raised in status.' },
  { id: 38, arabic: 'الْكَبِيرُ', transliteration: 'Al-Kabir', meaning: 'The Great', urduMeaning: 'سب سے بڑا', benefit: 'Recite to overcome pride and ego.' },
  { id: 39, arabic: 'الْحَفِيظُ', transliteration: 'Al-Hafiz', meaning: 'The Preserver', urduMeaning: 'محافظ', benefit: 'Recite for protection of yourself and family.' },
  { id: 40, arabic: 'الْمُقِيتُ', transliteration: 'Al-Muqit', meaning: 'The Nourisher', urduMeaning: 'نگہبان', benefit: 'Recite for nourishment of body and soul.' },
  { id: 41, arabic: 'الْحَسِيبُ', transliteration: 'Al-Hasib', meaning: 'The Reckoner', urduMeaning: 'حساب لینے والا', benefit: 'Recite for protection from evil.' },
  { id: 42, arabic: 'الْجَلِيلُ', transliteration: 'Al-Jalil', meaning: 'The Majestic', urduMeaning: 'جلیل', benefit: 'Recite to gain dignity and reverence.' },
  { id: 43, arabic: 'الْكَرِيمُ', transliteration: 'Al-Karim', meaning: 'The Generous', urduMeaning: 'کریم', benefit: 'Recite for generosity and abundance.' },
  { id: 44, arabic: 'الرَّقِيبُ', transliteration: 'Ar-Raqib', meaning: 'The Watchful', urduMeaning: 'نگران', benefit: 'Recite to keep yourself accountable.' },
  { id: 45, arabic: 'الْمُجِيبُ', transliteration: 'Al-Mujib', meaning: 'The Responsive', urduMeaning: 'قبول کرنے والا', benefit: 'Recite for acceptance of duas.' },
  { id: 46, arabic: 'الْوَاسِعُ', transliteration: 'Al-Wasi', meaning: 'The All-Encompassing', urduMeaning: 'وسیع', benefit: 'Recite for expansion in all things.' },
  { id: 47, arabic: 'الْحَكِيمُ', transliteration: 'Al-Hakim', meaning: 'The Wise', urduMeaning: 'حکیم', benefit: 'Recite for wisdom in decisions.' },
  { id: 48, arabic: 'الْوَدُودُ', transliteration: 'Al-Wadud', meaning: 'The Loving', urduMeaning: 'محبت کرنے والا', benefit: 'Recite for love and affection.' },
  { id: 49, arabic: 'الْمَجِيدُ', transliteration: 'Al-Majid', meaning: 'The Glorious', urduMeaning: 'بزرگ', benefit: 'Recite for glory and honor.' },
  { id: 50, arabic: 'الْبَاعِثُ', transliteration: 'Al-Baith', meaning: 'The Resurrector', urduMeaning: 'اٹھانے والا', benefit: 'Recite to remember resurrection and prepare.' },
  { id: 51, arabic: 'الشَّهِيدُ', transliteration: 'Ash-Shahid', meaning: 'The Witness', urduMeaning: 'گواہ', benefit: 'Recite to keep yourself righteous.' },
  { id: 52, arabic: 'الْحَقُّ', transliteration: 'Al-Haqq', meaning: 'The Truth', urduMeaning: 'حق', benefit: 'Recite to distinguish truth from falsehood.' },
  { id: 53, arabic: 'الْوَكِيلُ', transliteration: 'Al-Wakil', meaning: 'The Trustee', urduMeaning: 'کارساز', benefit: 'Recite to put your trust in Allah.' },
  { id: 54, arabic: 'الْقَوِيُّ', transliteration: 'Al-Qawi', meaning: 'The Strong', urduMeaning: 'قوت والا', benefit: 'Recite to gain strength in adversity.' },
  { id: 55, arabic: 'الْمَتِينُ', transliteration: 'Al-Matin', meaning: 'The Firm', urduMeaning: 'مضبوط', benefit: 'Recite for firmness and steadfastness.' },
  { id: 56, arabic: 'الْوَلِيُّ', transliteration: 'Al-Wali', meaning: 'The Guardian', urduMeaning: 'ولی', benefit: 'Recite for divine guardianship.' },
  { id: 57, arabic: 'الْحَمِيدُ', transliteration: 'Al-Hamid', meaning: 'The Praiseworthy', urduMeaning: 'تعریف کے لائق', benefit: 'Recite to increase praise and gratitude.' },
  { id: 58, arabic: 'الْمُحْصِي', transliteration: 'Al-Muhsi', meaning: 'The All-Enumerating', urduMeaning: 'گننے والا', benefit: 'Recite to be mindful of actions.' },
  { id: 59, arabic: 'الْمُبْدِئُ', transliteration: 'Al-Mubdi', meaning: 'The Originator', urduMeaning: 'ابتدا کرنے والا', benefit: 'Recite for new beginnings.' },
  { id: 60, arabic: 'الْمُعِيدُ', transliteration: 'Al-Muid', meaning: 'The Restorer', urduMeaning: 'لوٹانے والا', benefit: 'Recite to restore what has been lost.' },
  { id: 61, arabic: 'الْمُحْيِي', transliteration: 'Al-Muhyi', meaning: 'The Giver of Life', urduMeaning: 'زندگی دینے والا', benefit: 'Recite for revival of spirituality.' },
  { id: 62, arabic: 'الْمُمِيتُ', transliteration: 'Al-Mumit', meaning: 'The Taker of Life', urduMeaning: 'موت دینے والا', benefit: 'Recite to remember mortality and prepare.' },
  { id: 63, arabic: 'الْحَيُّ', transliteration: 'Al-Hayy', meaning: 'The Ever-Living', urduMeaning: 'زندہ', benefit: 'Recite for spiritual liveliness and health.' },
  { id: 64, arabic: 'الْقَيُّومُ', transliteration: 'Al-Qayyum', meaning: 'The Self-Subsisting', urduMeaning: 'قائم', benefit: 'Recite for self-sufficiency and stability.' },
  { id: 65, arabic: 'الْوَاجِدُ', transliteration: 'Al-Wajid', meaning: 'The Perceiver', urduMeaning: 'غنی', benefit: 'Recite to find what you have lost.' },
  { id: 66, arabic: 'الْمَاجِدُ', transliteration: 'Al-Majid', meaning: 'The Glorious', urduMeaning: 'مجید', benefit: 'Recite for nobility and glory.' },
  { id: 67, arabic: 'الْوَاحِدُ', transliteration: 'Al-Wahid', meaning: 'The One', urduMeaning: 'ایک', benefit: 'Recite for unity and focus.' },
  { id: 68, arabic: 'الأَحَدُ', transliteration: 'Al-Ahad', meaning: 'The Unique', urduMeaning: 'یکتا', benefit: 'Recite to affirm Allah\'s oneness.' },
  { id: 69, arabic: 'الصَّمَدُ', transliteration: 'As-Samad', meaning: 'The Eternal', urduMeaning: 'بے نیاز', benefit: 'Recite to feel that Allah is sufficient.' },
  { id: 70, arabic: 'الْقَادِرُ', transliteration: 'Al-Qadir', meaning: 'The Capable', urduMeaning: 'قادر', benefit: 'Recite for ability and power.' },
  { id: 71, arabic: 'الْمُقْتَدِرُ', transliteration: 'Al-Muqtadir', meaning: 'The Powerful', urduMeaning: 'بہت قادر', benefit: 'Recite to overcome powerlessness.' },
  { id: 72, arabic: 'الْمُقَدِّمُ', transliteration: 'Al-Muqaddim', meaning: 'The Expediter', urduMeaning: 'آگے کرنے والا', benefit: 'Recite for advancement.' },
  { id: 73, arabic: 'الْمُؤَخِّرُ', transliteration: 'Al-Muakhkhir', meaning: 'The Delayer', urduMeaning: 'پیچھے کرنے والا', benefit: 'Recite for acceptance of divine timing.' },
  { id: 74, arabic: 'الأَوَّلُ', transliteration: 'Al-Awwal', meaning: 'The First', urduMeaning: 'اول', benefit: 'Recite to remember Allah is before everything.' },
  { id: 75, arabic: 'الآخِرُ', transliteration: 'Al-Akhir', meaning: 'The Last', urduMeaning: 'آخر', benefit: 'Recite to remember all returns to Allah.' },
  { id: 76, arabic: 'الظَّاهِرُ', transliteration: 'Az-Zahir', meaning: 'The Manifest', urduMeaning: 'ظاہر', benefit: 'Recite to see signs of Allah.' },
  { id: 77, arabic: 'الْبَاطِنُ', transliteration: 'Al-Batin', meaning: 'The Hidden', urduMeaning: 'باطن', benefit: 'Recite for inner knowledge.' },
  { id: 78, arabic: 'الْوَالِي', transliteration: 'Al-Wali', meaning: 'The Governor', urduMeaning: 'والی', benefit: 'Recite for divine governance in affairs.' },
  { id: 79, arabic: 'الْمُتَعَالِي', transliteration: 'Al-Mutaali', meaning: 'The Most Exalted', urduMeaning: 'سب سے بلند', benefit: 'Recite to understand Allah\'s transcendence.' },
  { id: 80, arabic: 'الْبَرُّ', transliteration: 'Al-Barr', meaning: 'The Source of Goodness', urduMeaning: 'نیکی کرنے والا', benefit: 'Recite for goodness and righteousness.' },
  { id: 81, arabic: 'التَّوَّابُ', transliteration: 'At-Tawwab', meaning: 'The Ever-Relenting', urduMeaning: 'توبہ قبول کرنے والا', benefit: 'Recite for repentance to be accepted.' },
  { id: 82, arabic: 'الْمُنْتَقِمُ', transliteration: 'Al-Muntaqim', meaning: 'The Avenger', urduMeaning: 'انتقام لینے والا', benefit: 'Recite for justice against oppressors.' },
  { id: 83, arabic: 'الْعَفُوُّ', transliteration: 'Al-Afuww', meaning: 'The Pardoner', urduMeaning: 'معاف کرنے والا', benefit: 'Recite for complete pardon of sins.' },
  { id: 84, arabic: 'الرَّؤُوفُ', transliteration: 'Ar-Rauf', meaning: 'The Compassionate', urduMeaning: 'شفیق', benefit: 'Recite for gentleness and compassion.' },
  { id: 85, arabic: 'مَالِكُ الْمُلْكِ', transliteration: 'Malik-ul-Mulk', meaning: 'Master of the Kingdom', urduMeaning: 'سلطنت کا مالک', benefit: 'Recite for dominion and authority.' },
  { id: 86, arabic: 'ذُو الْجَلاَلِ وَالإِكْرَامِ', transliteration: 'Dhul-Jalali wal-Ikram', meaning: 'Lord of Majesty and Bounty', urduMeaning: 'جلال و اکرام والا', benefit: 'Recite for Allah\'s majesty and generosity.' },
  { id: 87, arabic: 'الْمُقْسِطُ', transliteration: 'Al-Muqsit', meaning: 'The Equitable', urduMeaning: 'انصاف کرنے والا', benefit: 'Recite for fairness in dealings.' },
  { id: 88, arabic: 'الْجَامِعُ', transliteration: 'Al-Jami', meaning: 'The Gatherer', urduMeaning: 'جمع کرنے والا', benefit: 'Recite to unite loved ones.' },
  { id: 89, arabic: 'الْغَنِيُّ', transliteration: 'Al-Ghani', meaning: 'The Self-Sufficient', urduMeaning: 'غنی', benefit: 'Recite for freedom from need.' },
  { id: 90, arabic: 'الْمُغْنِي', transliteration: 'Al-Mughni', meaning: 'The Enricher', urduMeaning: 'غنی کرنے والا', benefit: 'Recite for wealth and sufficiency.' },
  { id: 91, arabic: 'الْمَانِعُ', transliteration: 'Al-Mani', meaning: 'The Preventer', urduMeaning: 'روکنے والا', benefit: 'Recite for protection from harm.' },
  { id: 92, arabic: 'الضَّارُّ', transliteration: 'Ad-Darr', meaning: 'The Distresser', urduMeaning: 'نقصان پہنچانے والا', benefit: 'Recite to seek relief from hardship.' },
  { id: 93, arabic: 'النَّافِعُ', transliteration: 'An-Nafi', meaning: 'The Benefiter', urduMeaning: 'فائدہ دینے والا', benefit: 'Recite for benefit and goodness.' },
  { id: 94, arabic: 'النُّورُ', transliteration: 'An-Nur', meaning: 'The Light', urduMeaning: 'نور', benefit: 'Recite for guidance and illumination.' },
  { id: 95, arabic: 'الْهَادِي', transliteration: 'Al-Hadi', meaning: 'The Guide', urduMeaning: 'رہنما', benefit: 'Recite for guidance on the right path.' },
  { id: 96, arabic: 'الْبَدِيعُ', transliteration: 'Al-Badi', meaning: 'The Originator', urduMeaning: 'انوکھا', benefit: 'Recite for creative inspiration.' },
  { id: 97, arabic: 'الْبَاقِي', transliteration: 'Al-Baqi', meaning: 'The Everlasting', urduMeaning: 'باقی', benefit: 'Recite to focus on what is eternal.' },
  { id: 98, arabic: 'الْوَارِثُ', transliteration: 'Al-Warith', meaning: 'The Inheritor', urduMeaning: 'وارث', benefit: 'Recite to remember everything returns to Allah.' },
  { id: 99, arabic: 'الرَّشِيدُ', transliteration: 'Ar-Rashid', meaning: 'The Guide to the Right Path', urduMeaning: 'صحیح رہنما', benefit: 'Recite for wisdom in all affairs.' },
];
