export interface Surah {
  id: number;
  name: string;
  nameEnglish: string;
  meaning: string;
  revelationType: 'Meccan' | 'Medinan';
  totalAyahs: number;
}

export const SURAHS: Surah[] = [
  { id: 1, name: 'الفاتحة', nameEnglish: 'Al-Fatihah', meaning: 'The Opening', revelationType: 'Meccan', totalAyahs: 7 },
  { id: 2, name: 'البقرة', nameEnglish: 'Al-Baqarah', meaning: 'The Cow', revelationType: 'Medinan', totalAyahs: 286 },
  { id: 3, name: 'آل عمران', nameEnglish: "Ali 'Imran", meaning: 'Family of Imran', revelationType: 'Medinan', totalAyahs: 200 },
  { id: 4, name: 'النساء', nameEnglish: "An-Nisa'", meaning: 'The Women', revelationType: 'Medinan', totalAyahs: 176 },
  { id: 5, name: 'المائدة', nameEnglish: "Al-Ma'idah", meaning: 'The Table', revelationType: 'Medinan', totalAyahs: 120 },
  { id: 6, name: 'الأنعام', nameEnglish: "Al-An'am", meaning: 'The Cattle', revelationType: 'Meccan', totalAyahs: 165 },
  { id: 7, name: 'الأعراف', nameEnglish: "Al-A'raf", meaning: 'The Heights', revelationType: 'Meccan', totalAyahs: 206 },
  { id: 8, name: 'الأنفال', nameEnglish: 'Al-Anfal', meaning: 'The Spoils of War', revelationType: 'Medinan', totalAyahs: 75 },
  { id: 9, name: 'التوبة', nameEnglish: 'At-Tawbah', meaning: 'The Repentance', revelationType: 'Medinan', totalAyahs: 129 },
  { id: 10, name: 'يونس', nameEnglish: 'Yunus', meaning: 'Jonah', revelationType: 'Meccan', totalAyahs: 109 },
  { id: 11, name: 'هود', nameEnglish: 'Hud', meaning: 'Hud', revelationType: 'Meccan', totalAyahs: 123 },
  { id: 12, name: 'يوسف', nameEnglish: 'Yusuf', meaning: 'Joseph', revelationType: 'Meccan', totalAyahs: 111 },
  { id: 13, name: 'الرعد', nameEnglish: "Ar-Ra'd", meaning: 'The Thunder', revelationType: 'Medinan', totalAyahs: 43 },
  { id: 14, name: 'إبراهيم', nameEnglish: 'Ibrahim', meaning: 'Abraham', revelationType: 'Meccan', totalAyahs: 52 },
  { id: 15, name: 'الحجر', nameEnglish: 'Al-Hijr', meaning: 'The Rocky Tract', revelationType: 'Meccan', totalAyahs: 99 },
  { id: 16, name: 'النحل', nameEnglish: 'An-Nahl', meaning: 'The Bee', revelationType: 'Meccan', totalAyahs: 128 },
  { id: 17, name: 'الإسراء', nameEnglish: "Al-Isra'", meaning: 'The Night Journey', revelationType: 'Meccan', totalAyahs: 111 },
  { id: 18, name: 'الكهف', nameEnglish: 'Al-Kahf', meaning: 'The Cave', revelationType: 'Meccan', totalAyahs: 110 },
  { id: 19, name: 'مريم', nameEnglish: 'Maryam', meaning: 'Mary', revelationType: 'Meccan', totalAyahs: 98 },
  { id: 20, name: 'طه', nameEnglish: 'Ta-Ha', meaning: 'Ta-Ha', revelationType: 'Meccan', totalAyahs: 135 },
  { id: 21, name: 'الأنبياء', nameEnglish: "Al-Anbiya'", meaning: 'The Prophets', revelationType: 'Meccan', totalAyahs: 112 },
  { id: 22, name: 'الحج', nameEnglish: 'Al-Hajj', meaning: 'The Pilgrimage', revelationType: 'Medinan', totalAyahs: 78 },
  { id: 23, name: 'المؤمنون', nameEnglish: "Al-Mu'minun", meaning: 'The Believers', revelationType: 'Meccan', totalAyahs: 118 },
  { id: 24, name: 'النور', nameEnglish: 'An-Nur', meaning: 'The Light', revelationType: 'Medinan', totalAyahs: 64 },
  { id: 25, name: 'الفرقان', nameEnglish: 'Al-Furqan', meaning: 'The Criterion', revelationType: 'Meccan', totalAyahs: 77 },
  { id: 26, name: 'الشعراء', nameEnglish: "Ash-Shu'ara'", meaning: 'The Poets', revelationType: 'Meccan', totalAyahs: 227 },
  { id: 27, name: 'النمل', nameEnglish: 'An-Naml', meaning: 'The Ant', revelationType: 'Meccan', totalAyahs: 93 },
  { id: 28, name: 'القصص', nameEnglish: 'Al-Qasas', meaning: 'The Stories', revelationType: 'Meccan', totalAyahs: 88 },
  { id: 29, name: 'العنكبوت', nameEnglish: 'Al-Ankabut', meaning: 'The Spider', revelationType: 'Meccan', totalAyahs: 69 },
  { id: 30, name: 'الروم', nameEnglish: 'Ar-Rum', meaning: 'The Romans', revelationType: 'Meccan', totalAyahs: 60 },
  { id: 31, name: 'لقمان', nameEnglish: 'Luqman', meaning: 'Luqman', revelationType: 'Meccan', totalAyahs: 34 },
  { id: 32, name: 'السجدة', nameEnglish: 'As-Sajdah', meaning: 'The Prostration', revelationType: 'Meccan', totalAyahs: 30 },
  { id: 33, name: 'الأحزاب', nameEnglish: 'Al-Ahzab', meaning: 'The Confederates', revelationType: 'Medinan', totalAyahs: 73 },
  { id: 34, name: 'سبإ', nameEnglish: "Saba'", meaning: 'Sheba', revelationType: 'Meccan', totalAyahs: 54 },
  { id: 35, name: 'فاطر', nameEnglish: 'Fatir', meaning: 'The Originator', revelationType: 'Meccan', totalAyahs: 45 },
  { id: 36, name: 'يس', nameEnglish: 'Ya-Sin', meaning: 'Ya-Sin', revelationType: 'Meccan', totalAyahs: 83 },
  { id: 37, name: 'الصافات', nameEnglish: 'As-Saffat', meaning: 'Those Ranged in Ranks', revelationType: 'Meccan', totalAyahs: 182 },
  { id: 38, name: 'ص', nameEnglish: 'Sad', meaning: 'Sad', revelationType: 'Meccan', totalAyahs: 88 },
  { id: 39, name: 'الزمر', nameEnglish: 'Az-Zumar', meaning: 'The Groups', revelationType: 'Meccan', totalAyahs: 75 },
  { id: 40, name: 'غافر', nameEnglish: 'Ghafir', meaning: 'The Forgiver', revelationType: 'Meccan', totalAyahs: 85 },
  { id: 41, name: 'فصلت', nameEnglish: 'Fussilat', meaning: 'Explained in Detail', revelationType: 'Meccan', totalAyahs: 54 },
  { id: 42, name: 'الشورى', nameEnglish: 'Ash-Shura', meaning: 'The Consultation', revelationType: 'Meccan', totalAyahs: 53 },
  { id: 43, name: 'الزخرف', nameEnglish: 'Az-Zukhruf', meaning: 'The Gold Adornments', revelationType: 'Meccan', totalAyahs: 89 },
  { id: 44, name: 'الدخان', nameEnglish: 'Ad-Dukhan', meaning: 'The Smoke', revelationType: 'Meccan', totalAyahs: 59 },
  { id: 45, name: 'الجاثية', nameEnglish: 'Al-Jathiyah', meaning: 'The Crouching', revelationType: 'Meccan', totalAyahs: 37 },
  { id: 46, name: 'الأحقاف', nameEnglish: 'Al-Ahqaf', meaning: 'The Wind-Curved Sandhills', revelationType: 'Meccan', totalAyahs: 35 },
  { id: 47, name: 'محمد', nameEnglish: 'Muhammad', meaning: 'Muhammad', revelationType: 'Medinan', totalAyahs: 38 },
  { id: 48, name: 'الفتح', nameEnglish: 'Al-Fath', meaning: 'The Victory', revelationType: 'Medinan', totalAyahs: 29 },
  { id: 49, name: 'الحجرات', nameEnglish: 'Al-Hujurat', meaning: 'The Rooms', revelationType: 'Medinan', totalAyahs: 18 },
  { id: 50, name: 'ق', nameEnglish: 'Qaf', meaning: 'Qaf', revelationType: 'Meccan', totalAyahs: 45 },
  { id: 51, name: 'الذاريات', nameEnglish: 'Adh-Dhariyat', meaning: 'The Winnowing Winds', revelationType: 'Meccan', totalAyahs: 60 },
  { id: 52, name: 'الطور', nameEnglish: 'At-Tur', meaning: 'The Mount', revelationType: 'Meccan', totalAyahs: 49 },
  { id: 53, name: 'النجم', nameEnglish: 'An-Najm', meaning: 'The Star', revelationType: 'Meccan', totalAyahs: 62 },
  { id: 54, name: 'القمر', nameEnglish: 'Al-Qamar', meaning: 'The Moon', revelationType: 'Meccan', totalAyahs: 55 },
  { id: 55, name: 'الرحمن', nameEnglish: 'Ar-Rahman', meaning: 'The Most Gracious', revelationType: 'Medinan', totalAyahs: 78 },
  { id: 56, name: 'الواقعة', nameEnglish: "Al-Waqi'ah", meaning: 'The Inevitable', revelationType: 'Meccan', totalAyahs: 96 },
  { id: 57, name: 'الحديد', nameEnglish: 'Al-Hadid', meaning: 'The Iron', revelationType: 'Medinan', totalAyahs: 29 },
  { id: 58, name: 'المجادلة', nameEnglish: 'Al-Mujadila', meaning: 'The Pleading Woman', revelationType: 'Medinan', totalAyahs: 22 },
  { id: 59, name: 'الحشر', nameEnglish: 'Al-Hashr', meaning: 'The Exile', revelationType: 'Medinan', totalAyahs: 24 },
  { id: 60, name: 'الممتحنة', nameEnglish: 'Al-Mumtahanah', meaning: 'She that is to be Examined', revelationType: 'Medinan', totalAyahs: 13 },
  { id: 61, name: 'الصف', nameEnglish: 'As-Saf', meaning: 'The Ranks', revelationType: 'Medinan', totalAyahs: 14 },
  { id: 62, name: 'الجمعة', nameEnglish: "Al-Jumu'ah", meaning: 'Friday', revelationType: 'Medinan', totalAyahs: 11 },
  { id: 63, name: 'المنافقون', nameEnglish: 'Al-Munafiqun', meaning: 'The Hypocrites', revelationType: 'Medinan', totalAyahs: 11 },
  { id: 64, name: 'التغابن', nameEnglish: 'At-Taghabun', meaning: 'Mutual Disillusion', revelationType: 'Medinan', totalAyahs: 18 },
  { id: 65, name: 'الطلاق', nameEnglish: 'At-Talaq', meaning: 'The Divorce', revelationType: 'Medinan', totalAyahs: 12 },
  { id: 66, name: 'التحريم', nameEnglish: 'At-Tahrim', meaning: 'The Prohibition', revelationType: 'Medinan', totalAyahs: 12 },
  { id: 67, name: 'الملك', nameEnglish: 'Al-Mulk', meaning: 'The Sovereignty', revelationType: 'Meccan', totalAyahs: 30 },
  { id: 68, name: 'القلم', nameEnglish: 'Al-Qalam', meaning: 'The Pen', revelationType: 'Meccan', totalAyahs: 52 },
  { id: 69, name: 'الحاقة', nameEnglish: 'Al-Haqqah', meaning: 'The Reality', revelationType: 'Meccan', totalAyahs: 52 },
  { id: 70, name: 'المعارج', nameEnglish: "Al-Ma'arij", meaning: 'The Ascending Stairways', revelationType: 'Meccan', totalAyahs: 44 },
  { id: 71, name: 'نوح', nameEnglish: 'Nuh', meaning: 'Noah', revelationType: 'Meccan', totalAyahs: 28 },
  { id: 72, name: 'الجن', nameEnglish: 'Al-Jinn', meaning: 'The Jinn', revelationType: 'Meccan', totalAyahs: 28 },
  { id: 73, name: 'المزمل', nameEnglish: 'Al-Muzzammil', meaning: 'The Enshrouded One', revelationType: 'Meccan', totalAyahs: 20 },
  { id: 74, name: 'المدثر', nameEnglish: 'Al-Muddaththir', meaning: 'The Cloaked One', revelationType: 'Meccan', totalAyahs: 56 },
  { id: 75, name: 'القيامة', nameEnglish: 'Al-Qiyamah', meaning: 'The Resurrection', revelationType: 'Meccan', totalAyahs: 40 },
  { id: 76, name: 'الإنسان', nameEnglish: 'Al-Insan', meaning: 'The Human', revelationType: 'Medinan', totalAyahs: 31 },
  { id: 77, name: 'المرسلات', nameEnglish: 'Al-Mursalat', meaning: 'The Emissaries', revelationType: 'Meccan', totalAyahs: 50 },
  { id: 78, name: 'النبإ', nameEnglish: "An-Naba'", meaning: 'The Announcement', revelationType: 'Meccan', totalAyahs: 40 },
  { id: 79, name: 'النازعات', nameEnglish: "An-Nazi'at", meaning: 'Those who Drag Forth', revelationType: 'Meccan', totalAyahs: 46 },
  { id: 80, name: 'عبس', nameEnglish: 'Abasa', meaning: 'He Frowned', revelationType: 'Meccan', totalAyahs: 42 },
  { id: 81, name: 'التكوير', nameEnglish: 'At-Takwir', meaning: 'The Overthrowing', revelationType: 'Meccan', totalAyahs: 29 },
  { id: 82, name: 'الانفطار', nameEnglish: 'Al-Infitar', meaning: 'The Cleaving', revelationType: 'Meccan', totalAyahs: 19 },
  { id: 83, name: 'المطففين', nameEnglish: 'Al-Mutaffifin', meaning: 'The Defrauders', revelationType: 'Meccan', totalAyahs: 36 },
  { id: 84, name: 'الانشقاق', nameEnglish: 'Al-Inshiqaq', meaning: 'The Sundering', revelationType: 'Meccan', totalAyahs: 25 },
  { id: 85, name: 'البروج', nameEnglish: 'Al-Buruj', meaning: 'The Constellations', revelationType: 'Meccan', totalAyahs: 22 },
  { id: 86, name: 'الطارق', nameEnglish: 'At-Tariq', meaning: 'The Morning Star', revelationType: 'Meccan', totalAyahs: 17 },
  { id: 87, name: 'الأعلى', nameEnglish: "Al-A'la", meaning: 'The Most High', revelationType: 'Meccan', totalAyahs: 19 },
  { id: 88, name: 'الغاشية', nameEnglish: 'Al-Ghashiyah', meaning: 'The Overwhelming', revelationType: 'Meccan', totalAyahs: 26 },
  { id: 89, name: 'الفجر', nameEnglish: 'Al-Fajr', meaning: 'The Dawn', revelationType: 'Meccan', totalAyahs: 30 },
  { id: 90, name: 'البلد', nameEnglish: 'Al-Balad', meaning: 'The City', revelationType: 'Meccan', totalAyahs: 20 },
  { id: 91, name: 'الشمس', nameEnglish: 'Ash-Shams', meaning: 'The Sun', revelationType: 'Meccan', totalAyahs: 15 },
  { id: 92, name: 'الليل', nameEnglish: 'Al-Layl', meaning: 'The Night', revelationType: 'Meccan', totalAyahs: 21 },
  { id: 93, name: 'الضحى', nameEnglish: 'Ad-Duha', meaning: 'The Morning Hours', revelationType: 'Meccan', totalAyahs: 11 },
  { id: 94, name: 'الشرح', nameEnglish: 'Ash-Sharh', meaning: 'The Relief', revelationType: 'Meccan', totalAyahs: 8 },
  { id: 95, name: 'التين', nameEnglish: 'At-Tin', meaning: 'The Fig', revelationType: 'Meccan', totalAyahs: 8 },
  { id: 96, name: 'العلق', nameEnglish: "Al-'Alaq", meaning: 'The Clot', revelationType: 'Meccan', totalAyahs: 19 },
  { id: 97, name: 'القدر', nameEnglish: 'Al-Qadr', meaning: 'The Power', revelationType: 'Meccan', totalAyahs: 5 },
  { id: 98, name: 'البينة', nameEnglish: 'Al-Bayyinah', meaning: 'The Clear Proof', revelationType: 'Medinan', totalAyahs: 8 },
  { id: 99, name: 'الزلزلة', nameEnglish: 'Az-Zalzalah', meaning: 'The Earthquake', revelationType: 'Medinan', totalAyahs: 8 },
  { id: 100, name: 'العاديات', nameEnglish: "Al-'Adiyat", meaning: 'The Coursers', revelationType: 'Meccan', totalAyahs: 11 },
  { id: 101, name: 'القارعة', nameEnglish: "Al-Qari'ah", meaning: 'The Calamity', revelationType: 'Meccan', totalAyahs: 11 },
  { id: 102, name: 'التكاثر', nameEnglish: 'At-Takathur', meaning: 'Rivalry in World Increase', revelationType: 'Meccan', totalAyahs: 8 },
  { id: 103, name: 'العصر', nameEnglish: "Al-'Asr", meaning: 'The Declining Day', revelationType: 'Meccan', totalAyahs: 3 },
  { id: 104, name: 'الهمزة', nameEnglish: 'Al-Humazah', meaning: 'The Traducer', revelationType: 'Meccan', totalAyahs: 9 },
  { id: 105, name: 'الفيل', nameEnglish: 'Al-Fil', meaning: 'The Elephant', revelationType: 'Meccan', totalAyahs: 5 },
  { id: 106, name: 'قريش', nameEnglish: 'Quraysh', meaning: 'Quraysh', revelationType: 'Meccan', totalAyahs: 4 },
  { id: 107, name: 'الماعون', nameEnglish: "Al-Ma'un", meaning: 'The Small Kindnesses', revelationType: 'Meccan', totalAyahs: 7 },
  { id: 108, name: 'الكوثر', nameEnglish: 'Al-Kawthar', meaning: 'Abundance', revelationType: 'Meccan', totalAyahs: 3 },
  { id: 109, name: 'الكافرون', nameEnglish: 'Al-Kafirun', meaning: 'The Disbelievers', revelationType: 'Meccan', totalAyahs: 6 },
  { id: 110, name: 'النصر', nameEnglish: 'An-Nasr', meaning: 'The Divine Support', revelationType: 'Medinan', totalAyahs: 3 },
  { id: 111, name: 'المسد', nameEnglish: 'Al-Masad', meaning: 'The Palm Fiber', revelationType: 'Meccan', totalAyahs: 5 },
  { id: 112, name: 'الإخلاص', nameEnglish: 'Al-Ikhlas', meaning: 'The Sincerity', revelationType: 'Meccan', totalAyahs: 4 },
  { id: 113, name: 'الفلق', nameEnglish: 'Al-Falaq', meaning: 'The Daybreak', revelationType: 'Meccan', totalAyahs: 5 },
  { id: 114, name: 'الناس', nameEnglish: 'An-Nas', meaning: 'Mankind', revelationType: 'Meccan', totalAyahs: 6 },
];

export const TRANSLATION_EDITIONS = [
  { id: 'en.sahih', name: 'Sahih International', lang: 'en' },
  { id: 'en.pickthall', name: 'Pickthall', lang: 'en' },
  { id: 'en.yusufali', name: 'Yusuf Ali', lang: 'en' },
  { id: 'ur.maududi', name: 'Maududi (Urdu)', lang: 'ur' },
  { id: 'ur.jalandhry', name: 'Jalandhry (Urdu)', lang: 'ur' },
];

export const TAFSEER_EDITIONS = [
  { id: 'en.maududi', name: "Maududi (Tafheemul Quran)", lang: 'en' },
  { id: 'ar.muyassar', name: 'Al-Muyassar (Arabic)', lang: 'ar' },
  { id: 'ar.jalalayn', name: "Jalalayn (Arabic)", lang: 'ar' },
];
